### ISSUE TITLE
Update 3d registration tutorial

### ISSUE THREAD

**Issue by kate-sann5100** [Project-MONAI/tutorials#1056]
**Is your feature request related to a problem? Please describe.**
As the `extract_levels` implementation has been updated, the tutorial needs to be updated accordingly.

**Describe the solution you'd like**
Option 1: change `extract_levels` from [0, 1, 2, 3] to [3] to maintain the same model architecture as the pretrained weight.
Option 2: train a new model

**Describe alternatives you've considered**
Option 1 could be a quick fix during the training of option 2.

**Additional context**
N/A

**Comment by wyli** [comment]
thanks @kate-sann5100, I think option1 would be a good workaround for now. currently the ci is getting this error:
```
10:10:05  Running ./3d_registration/paired_lung_ct.ipynb
10:10:05  Checking PEP8 compliance...
10:10:05  Running notebook...
10:10:05  Before:
10:10:05      "max_epochs = 5\n",
10:10:05  After:
10:10:05      "max_epochs = 1\n",
10:10:05  Before:
10:10:05      "val_interval = 1\n",
10:10:05  After:
10:10:05      "val_interval = 1\n",
10:10:09  MONAI version: 1.0.0+120.gc8ef7fe1
10:10:09  Numpy version: 1.22.2
10:10:09  Pytorch version: 1.10.2+cu102
10:10:09  MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
10:10:09  MONAI rev id: c8ef7fe1ca3d2fbed135a60d288063d536a58eb6
10:10:09  MONAI __file__: /home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/__init__.py
10:10:09  
10:10:09  Optional dependencies:
10:10:09  Pytorch Ignite version: 0.4.10
10:10:09  Nibabel version: 4.0.2
10:10:09  scikit-image version: 0.19.3
10:10:09  Pillow version: 7.0.0
10:10:09  Tensorboard version: 2.11.0
10:10:09  gdown version: 4.5.3
10:10:09  TorchVision version: 0.11.3+cu102
10:10:09  tqdm version: 4.64.1
10:10:09  lmdb version: 1.3.0
10:10:09  psutil version: 5.9.2
10:10:09  pandas version: 1.1.5
10:10:09  einops version: 0.6.0
10:10:09  transformers version: 4.21.3
10:10:09  mlflow version: 2.0.1
10:10:09  pynrrd version: 1.0.0
10:10:09  
10:10:09  For details about installing the optional dependencies, please visit:
10:10:09      https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
10:10:09  
10:10:10  /opt/conda/lib/python3.8/site-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
10:10:10    warnings.warn(
10:23:01  
Executing:   0%|          | 0/35 [00:00<?, ?cell/s]
Executing:   3%|▎         | 1/35 [00:01<00:46,  1.37s/cell]
Executing:   9%|▊         | 3/35 [00:06<01:17,  2.42s/cell]
Executing:  14%|█▍        | 5/35 [00:10<01:00,  2.01s/cell]
Executing:  26%|██▌       | 9/35 [11:50<45:28, 104.95s/cell]
Executing:  49%|████▊     | 17/35 [11:53<11:44, 39.15s/cell]
Executing:  54%|█████▍    | 19/35 [11:57<08:37, 32.33s/cell]
Executing:  60%|██████    | 21/35 [12:00<06:02, 25.90s/cell]
Executing:  71%|███████▏  | 25/35 [12:46<03:25, 20.51s/cell]
Executing:  80%|████████  | 28/35 [12:46<01:42, 14.69s/cell]
Executing:  89%|████████▊ | 31/35 [12:48<00:42, 10.65s/cell]
Executing:  89%|████████▊ | 31/35 [12:50<01:39, 24.85s/cell]
10:23:01  /opt/conda/lib/python3.8/site-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
10:23:01    warnings.warn(
10:23:01  Traceback (most recent call last):
10:23:01    File "/opt/conda/bin/papermill", line 8, in <module>
10:23:01      sys.exit(papermill())
10:23:01    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
10:23:01      return self.main(*args, **kwargs)
10:23:01    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1055, in main
10:23:01      rv = self.invoke(ctx)
10:23:01    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
10:23:01      return ctx.invoke(self.callback, **ctx.params)
10:23:01    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 760, in invoke
10:23:01      return __callback(*args, **kwargs)
10:23:01    File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
10:23:01      return f(get_current_context(), *args, **kwargs)
10:23:01    File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
10:23:01      execute_notebook(
10:23:01    File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 128, in execute_notebook
10:23:01      raise_for_execution_errors(nb, output_path)
10:23:01    File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 232, in raise_for_execution_errors
10:23:01      raise error
10:23:01  papermill.exceptions.PapermillExecutionError: 
10:23:01  ---------------------------------------------------------------------------
10:23:01  Exception encountered at "In [15]":
10:23:01  ---------------------------------------------------------------------------
10:23:01  RuntimeError                              Traceback (most recent call last)
10:23:01  Cell In [15], line 4
10:23:01        2 dst = f"{root_dir}/pretrained_weight.pth"
10:23:01        3 download_url(resource, dst)
10:23:01  ----> 4 model.load_state_dict(torch.load(dst))
10:23:01  
10:23:01  File /opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py:1482, in Module.load_state_dict(self, state_dict, strict)
10:23:01     1477         error_msgs.insert(
10:23:01     1478             0, 'Missing key(s) in state_dict: {}. '.format(
10:23:01     1479                 ', '.join('"{}"'.format(k) for k in missing_keys)))
10:23:01     1481 if len(error_msgs) > 0:
10:23:01  -> 1482     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
10:23:01     1483                        self.__class__.__name__, "\n\t".join(error_msgs)))
10:23:01     1484 return _IncompatibleKeys(missing_keys, unexpected_keys)
10:23:01  
10:23:01  RuntimeError: Error(s) in loading state_dict for LocalNet:
10:23:01  	Missing key(s) in state_dict: "decode_deconvs.0.deconv.conv.weight", "decode_deconvs.0.deconv.adn.N.weight", "decode_deconvs.0.deconv.adn.N.bias", "decode_deconvs.0.deconv.adn.N.running_mean", "decode_deconvs.0.deconv.adn.N.running_var", "decode_deconvs.1.deconv.conv.weight", "decode_deconvs.1.deconv.adn.N.weight", "decode_deconvs.1.deconv.adn.N.bias", "decode_deconvs.1.deconv.adn.N.running_mean", "decode_deconvs.1.deconv.adn.N.running_var", "decode_deconvs.2.deconv.conv.weight", "decode_deconvs.2.deconv.adn.N.weight", "decode_deconvs.2.deconv.adn.N.bias", "decode_deconvs.2.deconv.adn.N.running_mean", "decode_deconvs.2.deconv.adn.N.running_var", "decode_convs.0.0.conv.weight", "decode_convs.0.0.adn.N.weight", "decode_convs.0.0.adn.N.bias", "decode_convs.0.0.adn.N.running_mean", "decode_convs.0.0.adn.N.running_var", "decode_convs.0.1.layers.0.conv.weight", "decode_convs.0.1.layers.1.conv.weight", "decode_convs.0.1.norms.0.weight", "decode_convs.0.1.norms.0.bias", "decode_convs.0.1.norms.0.running_mean", "decode_convs.0.1.norms.0.running_var", "decode_convs.0.1.norms.1.weight", "decode_convs.0.1.norms.1.bias", "decode_convs.0.1.norms.1.running_mean", "decode_convs.0.1.norms.1.running_var", "decode_convs.1.0.conv.weight", "decode_convs.1.0.adn.N.weight", "decode_convs.1.0.adn.N.bias", "decode_convs.1.0.adn.N.running_mean", "decode_convs.1.0.adn.N.running_var", "decode_convs.1.1.layers.0.conv.weight", "decode_convs.1.1.layers.1.conv.weight", "decode_convs.1.1.norms.0.weight", "decode_convs.1.1.norms.0.bias", "decode_convs.1.1.norms.0.running_mean", "decode_convs.1.1.norms.0.running_var", "decode_convs.1.1.norms.1.weight", "decode_convs.1.1.norms.1.bias", "decode_convs.1.1.norms.1.running_mean", "decode_convs.1.1.norms.1.running_var", "decode_convs.2.0.conv.weight", "decode_convs.2.0.adn.N.weight", "decode_convs.2.0.adn.N.bias", "decode_convs.2.0.adn.N.running_mean", "decode_convs.2.0.adn.N.running_var", "decode_convs.2.1.layers.0.conv.weight", "decode_convs.2.1.layers.1.conv.weight", "decode_convs.2.1.norms.0.weight", "decode_convs.2.1.norms.0.bias", "decode_convs.2.1.norms.0.running_mean", "decode_convs.2.1.norms.0.running_var", "decode_convs.2.1.norms.1.weight", "decode_convs.2.1.norms.1.bias", "decode_convs.2.1.norms.1.running_mean", "decode_convs.2.1.norms.1.running_var", "output_block.layers.1.conv.weight", "output_block.layers.2.conv.weight", "output_block.layers.3.conv.weight". 
10:23:01  	size mismatch for output_block.layers.0.conv.weight: copying a param with shape torch.Size([3, 256, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([3, 32, 3, 3, 3]).
```
