### ISSUE TITLE
Error encountered while running Hecktor tutorial for Head and Neck tumor segmentation

### ISSUE THREAD

**Issue by BSonya** [Project-MONAI/tutorials#1246]
Hi. I am trying to utilize the Hecktor tutorial for Head and Neck tumor segmentation on the Hecktor dataset. As a beginner, I decided to go with a small part of the dataset, just 5 pairs of CT and PET images initially (one in each training fold) for practice. However, after training all 5 folds, I encountered the following error: 

=> loaded checkpoint /content/tutorials/auto3dseg/tasks/hecktor22/work_dir/segresnet_0/model/model.pt (epoch 0) (best_metric 0.00010351023956900463)
Total parameters count 87165548 distributed False
Using custom transforms {'after_resample_transforms': [<hecktor_crop_neck_region.HecktorCropNeckRegion object at 0x7f8e6c222970>]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/transform.py", line 102, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/transform.py", line 66, in _apply_transform
    return transform(parameters)
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/spatial/dictionary.py", line 429, in inverse
    d[key] = self.spacing_transform.inverse(d[key])
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/spatial/array.py", line 620, in inverse
    return self.sp_resample.inverse(data)
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/spatial/array.py", line 325, in inverse
    transform = self.pop_transform(data)
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/inverse.py", line 206, in pop_transform
    return self.get_most_recent_transform(data, key, check, pop=True)
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/inverse.py", line 188, in get_most_recent_transform
    self.check_transforms_match(all_transforms[-1])
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/inverse.py", line 155, in check_transforms_match
    raise RuntimeError(
RuntimeError: Error SpatialResample getting the most recently applied invertible transform HecktorCropNeckRegion 140249676261744 != 140249676259392.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/transform.py", line 102, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/transform.py", line 66, in _apply_transform
    return transform(parameters)
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/post/dictionary.py", line 701, in __call__
    inverted = self.transform.inverse(input_dict)
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/compose.py", line 184, in inverse
    data = apply_transform(t.inverse, data, self.map_items, self.unpack_items, self.log_stats)
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/transform.py", line 129, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <bound method Spacingd.inverse of <monai.transforms.spatial.dictionary.Spacingd object at 0x7f8e6c2225e0>>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/monai/apps/auto3dseg/__main__.py", line 22, in <module>
    fire.Fire(
  File "/usr/local/lib/python3.9/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/monai/apps/auto3dseg/auto_runner.py", line 703, in run
    preds = ensembler(pred_param=self.pred_params)
  File "/usr/local/lib/python3.9/dist-packages/monai/apps/auto3dseg/ensemble_builder.py", line 160, in __call__
    pred = infer_instance.predict(predict_files=[file], predict_params=param)
  File "/usr/local/lib/python3.9/dist-packages/monai/apps/auto3dseg/bundle_gen.py", line 269, in predict
    return [inferer.infer(f) for f in ensure_tuple(predict_files)]
  File "/usr/local/lib/python3.9/dist-packages/monai/apps/auto3dseg/bundle_gen.py", line 269, in <listcomp>
    return [inferer.infer(f) for f in ensure_tuple(predict_files)]
  File "/content/tutorials/auto3dseg/tasks/hecktor22/work_dir/segresnet_0/scripts/infer.py", line 33, in infer
    pred = self.segmenter.infer_image(image_file, save_mask=False)
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/tutorials/auto3dseg/tasks/hecktor22/work_dir/segresnet_0/scripts/segmenter.py", line 1132, in infer_image
    pred = [post_transforms(x)["pred"] for x in decollate_batch(batch_data)]
  File "/content/tutorials/auto3dseg/tasks/hecktor22/work_dir/segresnet_0/scripts/segmenter.py", line 1132, in <listcomp>
    pred = [post_transforms(x)["pred"] for x in decollate_batch(batch_data)]
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/compose.py", line 174, in __call__
    input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items, self.log_stats)
  File "/usr/local/lib/python3.9/dist-packages/monai/transforms/transform.py", line 129, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.post.dictionary.Invertd object at 0x7f8e7a4534c0>

**Comment by BSonya** [comment]
Thankyou for your response. 
I am now trying to training on complete dataset using a single 12GB GPU but the training is either terminated with vs code crash or it takes too long (8-10hrs on a single epoch)!
Any suggestions for increasing the speed of training?

Environment:

OS --> ubuntu 22.04.2

Python version --> 3.10.11

MONAI version --> 1.1.0

Pytorch --> 2.0.0+CU117

GPU models and configuration

**Comment by wyli** [comment]
sure, are you using this example? https://github.com/Project-MONAI/tutorials/tree/main/auto3dseg/tasks/hecktor22 the latest monai v1.2.0 had various optimizations in terms of training speed and memory usage, please consider upgrading to monai 1.2 `pip install -U monai`

**Comment by BSonya** [comment]
Yes, I'm using the same example. 
I do have a different conda environment where I have installed monai 1.2. see the details below:

(hecktor22a) dlrs@spml1:~$ python -c "import monai; monai.config.print_config()"
MONAI version: 1.2.0rc7+13.gf355d1fc
Numpy version: 1.24.3
Pytorch version: 2.0.1+cu117
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: f355d1fc38c50e83e4f20ffe870c19a5814dc501
MONAI __file__: /home/dlrs/MONAI/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.11
ITK version: 5.3.0
Nibabel version: 5.1.0
scikit-image version: 0.21.0
Pillow version: 9.5.0
Tensorboard version: 2.13.0
gdown version: 4.7.1
TorchVision version: 0.15.2+cu117
tqdm version: 4.65.0
lmdb version: 1.4.1
psutil version: 5.9.5
pandas version: 2.0.2
einops version: 0.6.1
transformers version: 4.21.3
mlflow version: 2.4.0
pynrrd version: 1.0.0
When I switch to this env, the following error appears: 
(hecktor22a) dlrs@spml1:~/Desktop/tutorials/auto3dseg/tasks/hecktor22$ python hecktor22.py
2023-06-20 14:52:24,122 - INFO - AutoRunner using work directory ./work_dir
2023-06-20 14:52:24,126 - INFO - Loading input config input.yaml
2023-06-20 14:52:24,141 - INFO - Datalist was copied to work_dir: /home/dlrs/Desktop/tutorials/auto3dseg/tasks/hecktor22/work_dir/hecktor22_folds.json
2023-06-20 14:52:24,144 - INFO - Setting num_fold 5 based on the input datalist /home/dlrs/Desktop/tutorials/auto3dseg/tasks/hecktor22/work_dir/hecktor22_folds.json.
2023-06-20 14:52:24,269 - INFO - Skipping data analysis...
2023-06-20 14:52:24,269 - INFO - Skipping algorithm generation...
Traceback (most recent call last):
  File "/home/dlrs/Desktop/tutorials/auto3dseg/tasks/hecktor22/hecktor22.py", line 26, in <module>
    runner.run()
  File "/home/dlrs/MONAI/monai/apps/auto3dseg/auto_runner.py", line 804, in run
    self._train_algo_in_sequence(history)
  File "/home/dlrs/MONAI/monai/apps/auto3dseg/auto_runner.py", line 656, in _train_algo_in_sequence
    algo.train(self.train_params, self.device_setting)
  File "/home/dlrs/MONAI/monai/apps/auto3dseg/bundle_gen.py", line 261, in train
    self.device_setting.update(device_setting)
AttributeError: 'SegresnetAlgo' object has no attribute 'device_setting'

**Comment by wyli** [comment]
@myron could you please help? it seems the tutorial here https://github.com/Project-MONAI/tutorials/tree/main/auto3dseg/tasks/hecktor22 should be updated for v1.2...

**Comment by BSonya** [comment]
@myron do I need to increase RAM or something? Kindly help

**Comment by myron** [comment]
@BSonya  hi, hold on for 1-2 days, it's fixed, just needs to be updated on github
