### ISSUE TITLE
ensemble_byoc.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#1253]
**Describe the bug**
```
[2023-03-17T01:18:05.802Z] Running ./auto3dseg/notebooks/ensemble_byoc.ipynb
[2023-03-17T01:18:05.802Z] Checking PEP8 compliance...
[2023-03-17T01:18:06.364Z] Running notebook...
[2023-03-17T01:18:06.364Z] Before:
[2023-03-17T01:18:06.364Z]     "max_epochs = 2\n",
[2023-03-17T01:18:06.364Z] After:
[2023-03-17T01:18:06.364Z]     "max_epochs = 1\n",
[2023-03-17T01:18:10.524Z] MONAI version: 1.1.0+120.g66d0478e
[2023-03-17T01:18:10.524Z] Numpy version: 1.22.2
[2023-03-17T01:18:10.524Z] Pytorch version: 1.10.2+cu102
[2023-03-17T01:18:10.524Z] MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
[2023-03-17T01:18:10.524Z] MONAI rev id: 66d0478e777f6ee00e0197898b41bff97ae5776f
[2023-03-17T01:18:10.524Z] MONAI __file__: /home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/__init__.py
[2023-03-17T01:18:10.524Z] 
[2023-03-17T01:18:10.524Z] Optional dependencies:
[2023-03-17T01:18:10.524Z] Pytorch Ignite version: 0.4.11
[2023-03-17T01:18:10.524Z] ITK version: 5.3.0
[2023-03-17T01:18:10.524Z] Nibabel version: 5.0.1
[2023-03-17T01:18:10.524Z] scikit-image version: 0.19.3
[2023-03-17T01:18:10.524Z] Pillow version: 7.0.0
[2023-03-17T01:18:10.524Z] Tensorboard version: 2.9.0
[2023-03-17T01:18:10.524Z] gdown version: 4.6.4
[2023-03-17T01:18:10.524Z] TorchVision version: 0.11.3+cu102
[2023-03-17T01:18:10.524Z] tqdm version: 4.64.1
[2023-03-17T01:18:10.524Z] lmdb version: 1.4.0
[2023-03-17T01:18:10.524Z] psutil version: 5.9.4
[2023-03-17T01:18:10.524Z] pandas version: 1.1.5
[2023-03-17T01:18:10.524Z] einops version: 0.6.0
[2023-03-17T01:18:10.524Z] transformers version: 4.21.3
[2023-03-17T01:18:10.524Z] mlflow version: 2.2.2
[2023-03-17T01:18:10.524Z] pynrrd version: 1.0.0
[2023-03-17T01:18:10.524Z] 
[2023-03-17T01:18:10.524Z] For details about installing the optional dependencies, please visit:
[2023-03-17T01:18:10.524Z]     https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
[2023-03-17T01:18:10.524Z] 
[2023-03-17T01:18:11.890Z] papermill  --progress-bar -k python3
[2023-03-17T01:18:12.450Z] /usr/local/lib/python3.8/dist-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
[2023-03-17T01:18:12.450Z]   warnings.warn(
[2023-03-17T01:18:25.132Z] 
Executing:   0%|          | 0/15 [00:00<?, ?cell/s]
Executing:   7%|▋         | 1/15 [00:01<00:18,  1.29s/cell]
Executing:  20%|██        | 3/15 [00:05<00:24,  2.06s/cell]
Executing:  33%|███▎      | 5/15 [00:09<00:19,  1.91s/cell]
Executing:  60%|██████    | 9/15 [00:09<00:05,  1.20cell/s]
Executing:  87%|████████▋ | 13/15 [00:11<00:01,  1.60cell/s]
Executing:  87%|████████▋ | 13/15 [00:12<00:01,  1.05cell/s]
[2023-03-17T01:18:25.132Z] /usr/local/lib/python3.8/dist-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
[2023-03-17T01:18:25.132Z]   warnings.warn(
[2023-03-17T01:18:25.132Z] Traceback (most recent call last):
[2023-03-17T01:18:25.132Z]   File "/usr/local/bin/papermill", line 8, in <module>
[2023-03-17T01:18:25.132Z]     sys.exit(papermill())
[2023-03-17T01:18:25.132Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
[2023-03-17T01:18:25.132Z]     return self.main(*args, **kwargs)
[2023-03-17T01:18:25.132Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
[2023-03-17T01:18:25.132Z]     rv = self.invoke(ctx)
[2023-03-17T01:18:25.132Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
[2023-03-17T01:18:25.132Z]     return ctx.invoke(self.callback, **ctx.params)
[2023-03-17T01:18:25.132Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
[2023-03-17T01:18:25.132Z]     return __callback(*args, **kwargs)
[2023-03-17T01:18:25.132Z]   File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
[2023-03-17T01:18:25.132Z]     return f(get_current_context(), *args, **kwargs)
[2023-03-17T01:18:25.132Z]   File "/usr/local/lib/python3.8/dist-packages/papermill/cli.py", line 250, in papermill
[2023-03-17T01:18:25.132Z]     execute_notebook(
[2023-03-17T01:18:25.132Z]   File "/usr/local/lib/python3.8/dist-packages/papermill/execute.py", line 128, in execute_notebook
[2023-03-17T01:18:25.132Z]     raise_for_execution_errors(nb, output_path)
[2023-03-17T01:18:25.132Z]   File "/usr/local/lib/python3.8/dist-packages/papermill/execute.py", line 232, in raise_for_execution_errors
[2023-03-17T01:18:25.132Z]     raise error
[2023-03-17T01:18:25.132Z] papermill.exceptions.PapermillExecutionError: 
[2023-03-17T01:18:25.132Z] ---------------------------------------------------------------------------
[2023-03-17T01:18:25.132Z] Exception encountered at "In [6]":
[2023-03-17T01:18:25.132Z] ---------------------------------------------------------------------------
[2023-03-17T01:18:25.132Z] AttributeError                            Traceback (most recent call last)
[2023-03-17T01:18:25.132Z] Cell In[6], line 14
[2023-03-17T01:18:25.132Z]      11 ConfigParser.export_config_file(input, input_cfg)
[2023-03-17T01:18:25.132Z]      13 bundle_generator = BundleGen(algo_path=work_dir, data_stats_filename="data_stats.yaml", data_src_cfg_name=input_cfg)
[2023-03-17T01:18:25.132Z] ---> 14 bundle_generator.generate(work_dir, num_fold=2)
[2023-03-17T01:18:25.132Z]      15 history = bundle_generator.get_history()
[2023-03-17T01:18:25.132Z]      17 max_epochs = 1
[2023-03-17T01:18:25.132Z] 
[2023-03-17T01:18:25.132Z] File /home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/apps/auto3dseg/bundle_gen.py:521, in BundleGen.generate(self, output_folder, num_fold, gpu_customization, gpu_customization_specs)
[2023-03-17T01:18:25.132Z]     513     gen_algo.export_to_disk(
[2023-03-17T01:18:25.132Z]     514         output_folder,
[2023-03-17T01:18:25.132Z]     515         name,
[2023-03-17T01:18:25.132Z]    (...)
[2023-03-17T01:18:25.132Z]     518         gpu_customization_specs=gpu_customization_specs,
[2023-03-17T01:18:25.132Z]     519     )
[2023-03-17T01:18:25.132Z]     520 else:
[2023-03-17T01:18:25.132Z] --> 521     gen_algo.export_to_disk(output_folder, name, fold=f_id)
[2023-03-17T01:18:25.132Z]     522 algo_to_pickle(gen_algo, template_path=algo.template_path)
[2023-03-17T01:18:25.132Z]     523 self.history.append({name: gen_algo})
[2023-03-17T01:18:25.132Z] 
[2023-03-17T01:18:25.132Z] File /home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/apps/auto3dseg/bundle_gen.py:141, in BundleAlgo.export_to_disk(self, output_path, algo_name, **kwargs)
[2023-03-17T01:18:25.132Z]     139     self.output_path = self.template_path
[2023-03-17T01:18:25.132Z]     140 if kwargs.pop("fill_template", True):
[2023-03-17T01:18:25.132Z] --> 141     self.fill_records = self.fill_template_config(self.data_stats_files, self.output_path, **kwargs)
[2023-03-17T01:18:25.132Z]     142 logger.info(self.output_path)
[2023-03-17T01:18:25.132Z] 
[2023-03-17T01:18:25.132Z] File /home/jenkins/agent/workspace/Monai-notebooks/tuts/tutorials/auto3dseg/notebooks/ensemble_byoc_work_dir/algorithm_templates/segresnet2d/scripts/algo.py:50, in Segresnet2dAlgo.fill_template_config(self, data_stats_file, output_path, **kwargs)
[2023-03-17T01:18:25.132Z]      48     data_stats.read_config(str(data_stats_file))
[2023-03-17T01:18:25.132Z]      49 else:
[2023-03-17T01:18:25.132Z] ---> 50     data_stats.update(data_stats_file)
[2023-03-17T01:18:25.132Z]      52 data_src_cfg = ConfigParser(globals=False)
[2023-03-17T01:18:25.132Z]      53 if self.data_list_file is not None and os.path.exists(
[2023-03-17T01:18:25.132Z]      54     str(self.data_list_file)
[2023-03-17T01:18:25.132Z]      55 ):
[2023-03-17T01:18:25.132Z] 
[2023-03-17T01:18:25.132Z] File /home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/bundle/config_parser.py:235, in ConfigParser.update(self, pairs)
[2023-03-17T01:18:25.132Z]     226 def update(self, pairs: dict[str, Any]) -> None:
[2023-03-17T01:18:25.132Z]     227     """
[2023-03-17T01:18:25.132Z]     228     Set the ``id`` and the corresponding config content in pairs, see also :py:meth:`__setitem__`.
[2023-03-17T01:18:25.132Z]     229     For example, ``parser.update({"train#epoch": 100, "train#lr": 0.02})``
[2023-03-17T01:18:25.132Z]    (...)
[2023-03-17T01:18:25.132Z]     233 
[2023-03-17T01:18:25.132Z]     234     """
[2023-03-17T01:18:25.132Z] --> 235     for k, v in pairs.items():
[2023-03-17T01:18:25.132Z]     236         self[k] = v
[2023-03-17T01:18:25.132Z] 
[2023-03-17T01:18:25.132Z] AttributeError: 'str' object has no attribute 'items'
```

cc @mingxin-zheng @Nic-Ma  might come from the algo template updates

**Comment by mingxin-zheng** [comment]
I can replicate the error on my dev machine. Let me take a look. Thanks!

**Comment by mingxin-zheng** [comment]
This happens after [this PR] changes the data stats path. It would be nice to check whether the file exists or not in `BundleGen`, as well as update this notebook. I will submit PRs to fix both.
