### ISSUE TITLE
test auto3dseg/notebooks/auto3dseg_hello_world.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#1267]
```
[2023-03-23T04:42:20.987Z] Running ./auto3dseg/notebooks/auto3dseg_hello_world.ipynb
[2023-03-23T04:42:20.987Z] Checking PEP8 compliance...
[2023-03-23T04:42:21.914Z] Running notebook...
[2023-03-23T04:42:21.914Z] Before:
[2023-03-23T04:42:21.914Z]     "max_epochs = 2\n",
[2023-03-23T04:42:21.914Z] After:
[2023-03-23T04:42:21.914Z]     "max_epochs = 1\n",
[2023-03-23T04:42:26.073Z] MONAI version: 1.2.0rc2+5.g4f8bc596
[2023-03-23T04:42:26.073Z] Numpy version: 1.22.2
[2023-03-23T04:42:26.073Z] Pytorch version: 1.10.2+cu102
[2023-03-23T04:42:26.073Z] MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
[2023-03-23T04:42:26.073Z] MONAI rev id: 4f8bc596499981642dd71d30475d2fd212616958
[2023-03-23T04:42:26.073Z] MONAI __file__: /home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/__init__.py
[2023-03-23T04:42:26.073Z] 
[2023-03-23T04:42:26.073Z] Optional dependencies:
[2023-03-23T04:42:26.073Z] Pytorch Ignite version: 0.4.8
[2023-03-23T04:42:26.073Z] ITK version: 5.3.0
[2023-03-23T04:42:26.073Z] Nibabel version: 5.0.1
[2023-03-23T04:42:26.073Z] scikit-image version: 0.19.3
[2023-03-23T04:42:26.073Z] Pillow version: 7.0.0
[2023-03-23T04:42:26.073Z] Tensorboard version: 2.9.0
[2023-03-23T04:42:26.073Z] gdown version: 4.6.4
[2023-03-23T04:42:26.073Z] TorchVision version: 0.11.3+cu102
[2023-03-23T04:42:26.073Z] tqdm version: 4.64.1
[2023-03-23T04:42:26.073Z] lmdb version: 1.4.0
[2023-03-23T04:42:26.073Z] psutil version: 5.9.4
[2023-03-23T04:42:26.073Z] pandas version: 1.1.5
[2023-03-23T04:42:26.073Z] einops version: 0.6.0
[2023-03-23T04:42:26.073Z] transformers version: 4.21.3
[2023-03-23T04:42:26.073Z] mlflow version: 2.2.2
[2023-03-23T04:42:26.073Z] pynrrd version: 1.0.0
[2023-03-23T04:42:26.073Z] 
[2023-03-23T04:42:26.073Z] For details about installing the optional dependencies, please visit:
[2023-03-23T04:42:26.073Z]     https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
[2023-03-23T04:42:26.073Z] 
[2023-03-23T04:42:27.437Z] papermill  --progress-bar -k python3
[2023-03-23T04:42:28.001Z] /usr/local/lib/python3.8/dist-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
[2023-03-23T04:42:28.001Z]   warnings.warn(
[2023-03-23T04:42:39.745Z] 
Executing:   0%|          | 0/20 [00:00<?, ?cell/s]
Executing:   5%|▌         | 1/20 [00:01<00:24,  1.31s/cell]
Executing:  15%|█▌        | 3/20 [00:05<00:35,  2.07s/cell]
Executing:  25%|██▌       | 5/20 [00:09<00:28,  1.89s/cell]
Executing:  45%|████▌     | 9/20 [00:09<00:09,  1.21cell/s]
Executing:  55%|█████▌    | 11/20 [00:10<00:05,  1.56cell/s]
Executing:  65%|██████▌   | 13/20 [00:10<00:03,  2.05cell/s]
Executing:  65%|██████▌   | 13/20 [00:11<00:06,  1.13cell/s]
[2023-03-23T04:42:39.745Z] /usr/local/lib/python3.8/dist-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
[2023-03-23T04:42:39.745Z]   warnings.warn(
[2023-03-23T04:42:39.745Z] Traceback (most recent call last):
[2023-03-23T04:42:39.745Z]   File "/usr/local/bin/papermill", line 8, in <module>
[2023-03-23T04:42:39.745Z]     sys.exit(papermill())
[2023-03-23T04:42:39.745Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
[2023-03-23T04:42:39.745Z]     return self.main(*args, **kwargs)
[2023-03-23T04:42:39.745Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
[2023-03-23T04:42:39.745Z]     rv = self.invoke(ctx)
[2023-03-23T04:42:39.745Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
[2023-03-23T04:42:39.745Z]     return ctx.invoke(self.callback, **ctx.params)
[2023-03-23T04:42:39.745Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
[2023-03-23T04:42:39.745Z]     return __callback(*args, **kwargs)
[2023-03-23T04:42:39.745Z]   File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
[2023-03-23T04:42:39.745Z]     return f(get_current_context(), *args, **kwargs)
[2023-03-23T04:42:39.745Z]   File "/usr/local/lib/python3.8/dist-packages/papermill/cli.py", line 250, in papermill
[2023-03-23T04:42:39.745Z]     execute_notebook(
[2023-03-23T04:42:39.745Z]   File "/usr/local/lib/python3.8/dist-packages/papermill/execute.py", line 128, in execute_notebook
[2023-03-23T04:42:39.745Z]     raise_for_execution_errors(nb, output_path)
[2023-03-23T04:42:39.745Z]   File "/usr/local/lib/python3.8/dist-packages/papermill/execute.py", line 232, in raise_for_execution_errors
[2023-03-23T04:42:39.745Z]     raise error
[2023-03-23T04:42:39.745Z] papermill.exceptions.PapermillExecutionError: 
[2023-03-23T04:42:39.745Z] ---------------------------------------------------------------------------
[2023-03-23T04:42:39.745Z] Exception encountered at "In [6]":
[2023-03-23T04:42:39.745Z] ---------------------------------------------------------------------------
[2023-03-23T04:42:39.745Z] SameFileError                             Traceback (most recent call last)
[2023-03-23T04:42:39.745Z] Cell In[6], line 1
[2023-03-23T04:42:39.745Z] ----> 1 runner = AutoRunner(
[2023-03-23T04:42:39.745Z]       2     work_dir=work_dir,
[2023-03-23T04:42:39.745Z]       3     input={
[2023-03-23T04:42:39.745Z]       4         "modality": "MRI",
[2023-03-23T04:42:39.745Z]       5         "datalist": datalist_file,
[2023-03-23T04:42:39.745Z]       6         "dataroot": dataroot_dir,
[2023-03-23T04:42:39.745Z]       7     },
[2023-03-23T04:42:39.745Z]       8 )
[2023-03-23T04:42:39.745Z] 
[2023-03-23T04:42:39.745Z] File /home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/apps/auto3dseg/auto_runner.py:258, in AutoRunner.__init__(self, work_dir, input, algos, analyze, algo_gen, train, hpo, hpo_backend, ensemble, not_use_cache, templates_path_or_url, **kwargs)
[2023-03-23T04:42:39.745Z]     256 datalist_filename = os.path.join(self.work_dir, os.path.basename(self.data_src_cfg["datalist"]))
[2023-03-23T04:42:39.745Z]     257 if datalist_filename != self.data_src_cfg["datalist"]:
[2023-03-23T04:42:39.745Z] --> 258     shutil.copyfile(self.data_src_cfg["datalist"], datalist_filename)
[2023-03-23T04:42:39.745Z]     259     logger.info(f"Datalist was copied to work_dir: {datalist_filename}")
[2023-03-23T04:42:39.745Z]     261 # inspect and update folds
[2023-03-23T04:42:39.745Z] 
[2023-03-23T04:42:39.745Z] File /usr/lib/python3.8/shutil.py:244, in copyfile(src, dst, follow_symlinks)
[2023-03-23T04:42:39.745Z]     241 sys.audit("shutil.copyfile", src, dst)
[2023-03-23T04:42:39.745Z]     243 if _samefile(src, dst):
[2023-03-23T04:42:39.745Z] --> 244     raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
[2023-03-23T04:42:39.745Z]     246 file_size = 0
[2023-03-23T04:42:39.745Z]     247 for i, fn in enumerate([src, dst]):
[2023-03-23T04:42:39.745Z] 
[2023-03-23T04:42:39.745Z] SameFileError: './helloworld_work_dir/sim_datalist.json' and '/home/jenkins/agent/workspace/Monai-notebooks/tuts/tutorials/auto3dseg/notebooks/helloworld_work_dir/sim_datalist.json' are the same file
[2023-03-23T04:42:39.745Z] 
```

cc @myron @mingxin-zheng introduced by https://github.com/Project-MONAI/MONAI/pull/6204?

**Comment by mingxin-zheng** [comment]
Commented in the https://github.com/Project-MONAI/MONAI/pull/6204#discussion_r1145848588. Thanks!
