### ISSUE TITLE
Possible nnunet tutorial improvements

### ISSUE THREAD

**Issue by mingxin-zheng** [Project-MONAI/tutorials#1302]
**Describe the bug**

I would like to make some improvements in the nnU-Net tutorial:
- Make environment installation consistent with other MONAI dev packages, for example, user can install with `pip install monai[nnunet]`. Also, `dev` branch of MONAI should not be required 
- Use one dataset in all the commands. Now one command uses MSD Spleen and MSD Prostate.
- Since datalists and input were used, shall we promote [this directory](https://github.com/Project-MONAI/tutorials/tree/main/auto3dseg/tasks) to the root so that it can be shared between tutorials?

- this following command only runs
```
python -m monai.apps.nnunet nnUNetV2Runner convert_dataset --input_config "./input.yaml"
```

if I set these optional vars in the `input.yaml`
```
nnunet_preprocessed: "./work_dir/nnUNet_preprocessed" # optional
nnunet_raw: "./work_dir/nnUNet_raw_data_base" # optional
nnunet_results: "./work_dir/nnUNet_trained_models" # optional
```
But stills, I got 
```
python -m monai.apps.nnunet nnUNetV2Runner convert_dataset --input_config "./input.yaml"
2023-04-11 14:11:27,633 - WARNING - Dataset ID does not exist! Check input '.yaml' if this is unexpected.
2023-04-11 14:11:27,675 - WARNING - Input '.yaml' is incorrect.
```
- the purpose and difference of `convert_dataset` and `convert_msd_dataset` need to be highlighted.
- Following the readme, I get
```
root@ipp1-3399:/opt/toolkit/tutorials/monai/nnunet# python -m monai.apps.nnunet nnUNetV2Runner plan_and_process --input_config "./input.yaml"
2023-04-11 14:07:21,167 - WARNING - Fingerprint extraction...
Dataset001_Task09_Spleen
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/monai/apps/nnunet/__main__.py", line 95, in <module>
    fire.Fire({"nnUNetV2Runner": nnUNetV2Runner})
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/monai/apps/nnunet/nnunetv2_runner.py", line 364, in plan_and_process
    self.extract_fingerprints(fpe, npfp, verify_dataset_integrity, clean, verbose)
  File "/usr/local/lib/python3.8/dist-packages/monai/apps/nnunet/nnunetv2_runner.py", line 213, in extract_fingerprints
    extract_fingerprints([int(self.dataset_name_or_id)], fpe, npfp, verify_dataset_integrity, clean, verbose)
  File "/usr/local/lib/python3.8/dist-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 46, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/usr/local/lib/python3.8/dist-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 31, in extract_fingerprint_dataset
    fpe = fingerprint_extractor_class(dataset_id, num_processes, verbose=verbose)
  File "/usr/local/lib/python3.8/dist-packages/nnunetv2/experiment_planning/dataset_fingerprint/fingerprint_extractor.py", line 32, in __init__
    self.dataset_json = load_json(join(self.input_folder, 'dataset.json'))
  File "/usr/local/lib/python3.8/dist-packages/batchgenerators/utilities/file_and_folder_operations.py", line 68, in load_json
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './work_dir/nnUNet_raw_data_base/Dataset001_Task09_Spleen/dataset.json'
```

**Comment by dongyang0122** [comment]
The following is my "input.yaml" without running into any issue. What is your input `.yaml`?

modality: CT
datalist: "./msd_task09_spleen_folds.json"
dataroot: "/workspace/data/nnunet_test/test09"
nnunet_preprocessed: "./work_dir/nnUNet_preprocessed"
nnunet_raw: "./work_dir/nnUNet_raw_data_base"
nnunet_results: "./work_dir/nnUNet_trained_models"

**Comment by mingxin-zheng** [comment]
Hi @dongyang0122 , I used Task05_Prostate, and it failed with 

```
root@4503766:/opt/toolkit/tutorials/monai/nnunet# python -m monai.apps.nnunet nnUNetV2Runner run --input_config='./input.yaml'
2023-04-17 12:26:43,645 - WARNING - Dataset ID does not exist! Check input '.yaml' if this is unexpected.
2023-04-17 12:26:43,908 - WARNING - [info] num_input_channels: 2
2023-04-17 12:26:44,473 - WARNING - [info] num_foreground_classes: 2
2023-04-17 12:26:44,473 - WARNING - Input '.yaml' is incorrect.
2023-04-17 12:26:44,605 - WARNING - Fingerprint extraction...
Dataset001_Task05_Prostate
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/monai/apps/nnunet/__main__.py", line 95, in <module>
    fire.Fire({"nnUNetV2Runner": nnUNetV2Runner})
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/monai/apps/nnunet/nnunetv2_runner.py", line 744, in run
    self.plan_and_process()
  File "/usr/local/lib/python3.8/dist-packages/monai/apps/nnunet/nnunetv2_runner.py", line 364, in plan_and_process
    self.extract_fingerprints(fpe, npfp, verify_dataset_integrity, clean, verbose)
  File "/usr/local/lib/python3.8/dist-packages/monai/apps/nnunet/nnunetv2_runner.py", line 213, in extract_fingerprints
    extract_fingerprints([int(self.dataset_name_or_id)], fpe, npfp, verify_dataset_integrity, clean, verbose)
  File "/usr/local/lib/python3.8/dist-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 46, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/usr/local/lib/python3.8/dist-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 31, in extract_fingerprint_dataset
    fpe = fingerprint_extractor_class(dataset_id, num_processes, verbose=verbose)
  File "/usr/local/lib/python3.8/dist-packages/nnunetv2/experiment_planning/dataset_fingerprint/fingerprint_extractor.py", line 32, in __init__
    self.dataset_json = load_json(join(self.input_folder, 'dataset.json'))
  File "/usr/local/lib/python3.8/dist-packages/batchgenerators/utilities/file_and_folder_operations.py", line 68, in load_json
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './work_dir/nnUNet_raw_data_base/Dataset001_Task05_Prostate/dataset.json'
```

The same command works for Task09_Spleen. Here are my config and datalist files for each tasks:

[config_files.zip](https://github.com/Project-MONAI/tutorials/files/11250076/config_files.zip)
