### ISSUE TITLE
deployment/ray/mednist_classifier_ray.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#1307]
**Describe the bug**
```
[2023-04-12T03:18:09.303Z] Running ./deployment/ray/mednist_classifier_ray.ipynb
[2023-04-12T03:18:09.303Z] Checking PEP8 compliance...
[2023-04-12T03:18:10.232Z] Running notebook...
[2023-04-12T03:18:14.391Z] MONAI version: 1.2.0rc2+44.g6a7f35b7
[2023-04-12T03:18:14.391Z] Numpy version: 1.22.2
[2023-04-12T03:18:14.391Z] Pytorch version: 1.10.2+cu102
[2023-04-12T03:18:14.391Z] MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
[2023-04-12T03:18:14.391Z] MONAI rev id: 6a7f35b7e271cdf3b2c763ae35acf4ab25d85d23
[2023-04-12T03:18:14.391Z] MONAI __file__: /home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/__init__.py
[2023-04-12T03:18:14.391Z] 
[2023-04-12T03:18:14.391Z] Optional dependencies:
[2023-04-12T03:18:14.391Z] Pytorch Ignite version: 0.4.11
[2023-04-12T03:18:14.391Z] ITK version: 5.3.0
[2023-04-12T03:18:14.391Z] Nibabel version: 5.1.0
[2023-04-12T03:18:14.391Z] scikit-image version: 0.19.3
[2023-04-12T03:18:14.391Z] Pillow version: 9.5.0
[2023-04-12T03:18:14.391Z] Tensorboard version: 2.9.0
[2023-04-12T03:18:14.391Z] gdown version: 4.7.1
[2023-04-12T03:18:14.391Z] TorchVision version: 0.11.3+cu102
[2023-04-12T03:18:14.391Z] tqdm version: 4.65.0
[2023-04-12T03:18:14.391Z] lmdb version: 1.4.1
[2023-04-12T03:18:14.391Z] psutil version: 5.9.4
[2023-04-12T03:18:14.391Z] pandas version: 1.1.5
[2023-04-12T03:18:14.391Z] einops version: 0.6.0
[2023-04-12T03:18:14.391Z] transformers version: 4.21.3
[2023-04-12T03:18:14.391Z] mlflow version: 2.2.2
[2023-04-12T03:18:14.391Z] pynrrd version: 1.0.0
[2023-04-12T03:18:14.391Z] 
[2023-04-12T03:18:14.391Z] For details about installing the optional dependencies, please visit:
[2023-04-12T03:18:14.391Z]     https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
[2023-04-12T03:18:14.391Z] 
[2023-04-12T03:18:16.275Z] papermill  --progress-bar -k python3
[2023-04-12T03:18:16.531Z] /usr/local/lib/python3.8/dist-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
[2023-04-12T03:18:16.531Z]   warnings.warn(
[2023-04-12T03:18:50.608Z] 
Executing:   0%|          | 0/27 [00:00<?, ?cell/s]
Executing:   4%|▎         | 1/27 [00:01<00:39,  1.53s/cell]
Executing:  15%|█▍        | 4/27 [00:23<02:22,  6.18s/cell]
Executing:  22%|██▏       | 6/27 [00:27<01:30,  4.31s/cell]
Executing:  41%|████      | 11/27 [00:31<00:35,  2.23s/cell]*** SIGTERM received at time=1681269530 on cpu 5 ***
[2023-04-12T03:18:50.608Z] PC: @     0x7f81decf246e  (unknown)  epoll_wait
[2023-04-12T03:18:50.608Z]     @     0x7f81dec16090  (unknown)  (unknown)
[2023-04-12T03:18:50.608Z] [2023-04-12 03:18:50,337 E 11614 11614] logging.cc:361: *** SIGTERM received at time=1681269530 on cpu 5 ***
[2023-04-12T03:18:50.608Z] [2023-04-12 03:18:50,337 E 11614 11614] logging.cc:361: PC: @     0x7f81decf246e  (unknown)  epoll_wait
[2023-04-12T03:18:50.608Z] [2023-04-12 03:18:50,337 E 11614 11614] logging.cc:361:     @     0x7f81dec16090  (unknown)  (unknown)
[2023-04-12T03:18:53.124Z] 
Executing:  41%|████      | 11/27 [00:36<00:53,  3.33s/cell]
[2023-04-12T03:18:53.124Z] /usr/local/lib/python3.8/dist-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
[2023-04-12T03:18:53.124Z]   warnings.warn(
[2023-04-12T03:18:53.124Z] Traceback (most recent call last):
[2023-04-12T03:18:53.124Z]   File "/usr/local/bin/papermill", line 8, in <module>
[2023-04-12T03:18:53.124Z]     sys.exit(papermill())
[2023-04-12T03:18:53.124Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
[2023-04-12T03:18:53.124Z]     return self.main(*args, **kwargs)
[2023-04-12T03:18:53.124Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
[2023-04-12T03:18:53.124Z]     rv = self.invoke(ctx)
[2023-04-12T03:18:53.124Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
[2023-04-12T03:18:53.124Z]     return ctx.invoke(self.callback, **ctx.params)
[2023-04-12T03:18:53.124Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
[2023-04-12T03:18:53.124Z]     return __callback(*args, **kwargs)
[2023-04-12T03:18:53.124Z]   File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
[2023-04-12T03:18:53.124Z]     return f(get_current_context(), *args, **kwargs)
[2023-04-12T03:18:53.124Z]   File "/usr/local/lib/python3.8/dist-packages/papermill/cli.py", line 250, in papermill
[2023-04-12T03:18:53.124Z]     execute_notebook(
[2023-04-12T03:18:53.124Z]   File "/usr/local/lib/python3.8/dist-packages/papermill/execute.py", line 128, in execute_notebook
[2023-04-12T03:18:53.124Z]     raise_for_execution_errors(nb, output_path)
[2023-04-12T03:18:53.124Z]   File "/usr/local/lib/python3.8/dist-packages/papermill/execute.py", line 232, in raise_for_execution_errors
[2023-04-12T03:18:53.124Z]     raise error
[2023-04-12T03:18:53.124Z] papermill.exceptions.PapermillExecutionError: 
[2023-04-12T03:18:53.124Z] ---------------------------------------------------------------------------
[2023-04-12T03:18:53.124Z] Exception encountered at "In [5]":
[2023-04-12T03:18:53.124Z] ---------------------------------------------------------------------------
[2023-04-12T03:18:53.124Z] RayActorError                             Traceback (most recent call last)
[2023-04-12T03:18:53.124Z] Cell In[5], line 1
[2023-04-12T03:18:53.124Z] ----> 1 serve.start()
[2023-04-12T03:18:53.124Z]       2 MedNISTClassifier.deploy()
[2023-04-12T03:18:53.124Z] 
[2023-04-12T03:18:53.124Z] File /usr/local/lib/python3.8/dist-packages/ray/serve/api.py:100, in start(detached, http_options, dedicated_cpu, **kwargs)
[2023-04-12T03:18:53.124Z]      54 @guarded_deprecation_warning(instructions=MIGRATION_MESSAGE)
[2023-04-12T03:18:53.124Z]      55 @Deprecated(message=MIGRATION_MESSAGE)
[2023-04-12T03:18:53.124Z]      56 def start(
[2023-04-12T03:18:53.124Z]    (...)
[2023-04-12T03:18:53.124Z]      60     **kwargs,
[2023-04-12T03:18:53.124Z]      61 ) -> ServeControllerClient:
[2023-04-12T03:18:53.124Z]      62     """Initialize a serve instance.
[2023-04-12T03:18:53.124Z]      63 
[2023-04-12T03:18:53.124Z]      64     By default, the instance will be scoped to the lifetime of the returned
[2023-04-12T03:18:53.124Z]    (...)
[2023-04-12T03:18:53.124Z]      98           Serve controller actor.  Defaults to False.
[2023-04-12T03:18:53.124Z]      99     """
[2023-04-12T03:18:53.124Z] --> 100     client = _private_api.serve_start(detached, http_options, dedicated_cpu, **kwargs)
[2023-04-12T03:18:53.124Z]     102     # Record after Ray has been started.
[2023-04-12T03:18:53.124Z]     103     record_extra_usage_tag(TagKey.SERVE_API_VERSION, "v1")
[2023-04-12T03:18:53.124Z] 
[2023-04-12T03:18:53.124Z] File /usr/local/lib/python3.8/dist-packages/ray/serve/_private/api.py:236, in serve_start(detached, http_options, dedicated_cpu, **kwargs)
[2023-04-12T03:18:53.124Z]     227     http_options = HTTPOptions()
[2023-04-12T03:18:53.124Z]     229 controller = ServeController.options(**controller_actor_options).remote(
[2023-04-12T03:18:53.124Z]     230     controller_name,
[2023-04-12T03:18:53.124Z]     231     http_config=http_options,
[2023-04-12T03:18:53.124Z]     232     head_node_id=head_node_id,
[2023-04-12T03:18:53.124Z]     233     detached=detached,
[2023-04-12T03:18:53.124Z]     234 )
[2023-04-12T03:18:53.124Z] --> 236 proxy_handles = ray.get(controller.get_http_proxies.remote())
[2023-04-12T03:18:53.124Z]     237 if len(proxy_handles) > 0:
[2023-04-12T03:18:53.124Z]     238     try:
[2023-04-12T03:18:53.124Z] 
[2023-04-12T03:18:53.124Z] File /usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
[2023-04-12T03:18:53.124Z]     103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
[2023-04-12T03:18:53.124Z]     104         return getattr(ray, func.__name__)(*args, **kwargs)
[2023-04-12T03:18:53.124Z] --> 105 return func(*args, **kwargs)
[2023-04-12T03:18:53.124Z] 
[2023-04-12T03:18:53.124Z] File /usr/local/lib/python3.8/dist-packages/ray/_private/worker.py:2382, in get(object_refs, timeout)
[2023-04-12T03:18:53.124Z]    2380             raise value.as_instanceof_cause()
[2023-04-12T03:18:53.124Z]    2381         else:
[2023-04-12T03:18:53.124Z] -> 2382             raise value
[2023-04-12T03:18:53.124Z]    2384 if is_individual_id:
[2023-04-12T03:18:53.124Z]    2385     values = values[0]
[2023-04-12T03:18:53.124Z] 
[2023-04-12T03:18:53.124Z] RayActorError: The actor died unexpectedly before finishing this task.
[2023-04-12T03:18:53.124Z] 	class_name: ServeController
[2023-04-12T03:18:53.124Z] 	actor_id: 6ec82977fa4d1a9958a4b8f701000000
[2023-04-12T03:18:53.124Z] 	name: SERVE_CONTROLLER_ACTOR:WCUrZZ
[2023-04-12T03:18:53.124Z] 	namespace: serve
[2023-04-12T03:18:53.124Z] The actor is dead because its owner has died. O Owner worker exit type: SYSTEM_ERROR Worker exit detail: Owner's node has crashed.
[2023-04-12T03:18:53.124Z] The actor never ran - it was cancelled before it started running.
[2023-04-12T03:18:53.124Z] 
```

cc @Nic-Ma

**Comment by wyli** [comment]
Hi @ericspod  could you please help review the notebook? https://github.com/Project-MONAI/tutorials/blob/main/deployment/ray/mednist_classifier_ray.ipynb if it's a testing environment issue I'll change the script to skip the test.

**Comment by ericspod** [comment]
hi @wyli, I'm not sure what's causing this. I can run the notebook through all the way in Colab without any issues so it's possibly a timing problem. The startup and shutdown commands for Ray take a bit of time to execute so perhaps that's it, but for now if you wanted to skip this one it does appear to still be correct.

**Comment by wyli** [comment]
added to skip the test https://github.com/Project-MONAI/tutorials/blob/18314deed1070e81a6e0f4dc2729ae2b5bb59b57/runner.sh#L100
