### ISSUE TITLE
Auto3DSeg terminates after 1 epoch: returned non-zero exit status 1

### ISSUE THREAD

**Issue by Hirriririir** [Project-MONAI/tutorials#1367]
**---question---**
Hi guys great work. I'm having an issue with the Auto3DSeg pipeline. When I try to train my own data, the training process always terminates after 1 epoch. I've searched for similar issues, but I haven't been able to find any. I've also tried training the pipeline on different servers with different RAM and GPU configurations (best server: 120G RAM and NVIDIA A100 80GB PCIe) and different MONAI versions (monai-weekly and stable), but the issue persists.

Could you please help me debug this issue?

Thanks in advance!

**---config---**
```
/home/hua/miniconda3/envs/LGMD/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
MONAI version: 1.1.0
Numpy version: 1.23.1
Pytorch version: 1.12.1
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: a2ec3752f54bfc3b40e7952234fbeb5452ed63e3
MONAI __file__: /home/hua/miniconda3/envs/LGMD/lib/python3.8/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.10
Nibabel version: 4.0.2
scikit-image version: 0.19.3
Pillow version: 9.2.0
Tensorboard version: 2.12.2
gdown version: 4.7.1
TorchVision version: 0.13.1
tqdm version: 4.64.1
lmdb version: 1.4.0
psutil version: 5.9.0
pandas version: 1.4.4
einops version: 0.6.0
transformers version: 4.21.3
mlflow version: 2.2.2
pynrrd version: 1.0.0
```
**--- running tutorial code ---**
```
history = import_bundle_algo_history(work_dir, only_trained=False)
for algo_dict in history:
    algo = algo_dict[AlgoKeys.ALGO]
    algo.train(train_param)  # can use default params by `algo.train()`
    acc = algo.get_score()
    algo_to_pickle(algo, template_path=algo.template_path, best_metric=acc)
```

**--- output---**
```
2023-05-04 16:10:59,230 - INFO - The keys num_warmup_epochs cannot be found in the [./work_dir/dints_0/configs/hyper_parameters.yaml](https://vscode-remote+ssh-002dremote-002bfeaturize-0040workspace-002efeaturize-002ecn-003a58184.vscode-resource.vscode-cdn.net/home/featurize/work_dir/dints_0/configs/hyper_parameters.yaml) for training. Skipped overriding key num_warmup_epochs.
2023-05-04 16:10:59,232 - INFO - Launching: python [./work_dir/dints_0/scripts/train.py](https://vscode-remote+ssh-002dremote-002bfeaturize-0040workspace-002efeaturize-002ecn-003a58184.vscode-resource.vscode-cdn.net/home/featurize/work_dir/dints_0/scripts/train.py) run --config_file='work_dir/dints_0/configs/hyper_parameters.yaml','work_dir/dints_0/configs/hyper_parameters_search.yaml','work_dir/dints_0/configs/network.yaml','work_dir/dints_0/configs/network_search.yaml','work_dir/dints_0/configs/transforms_infer.yaml','work_dir/dints_0/configs/transforms_train.yaml','work_dir/dints_0/configs/transforms_validate.yaml' --training#num_epochs_per_validation=1 --training#num_images_per_batch=2 --training#num_epochs=2
2023-05-04 16:11:01.168547: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-04 16:11:02.292637: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-05-04 16:11:02.292714: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-05-04 16:11:02.292722: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
dints_0 - training ...:  50%|█████     | 1/2 [09:45<09:45, 585.80s/round]
Traceback (most recent call last):
  File "[./work_dir/dints_0/scripts/train.py](https://vscode-remote+ssh-002dremote-002bfeaturize-0040workspace-002efeaturize-002ecn-003a58184.vscode-resource.vscode-cdn.net/home/featurize/work_dir/dints_0/scripts/train.py)", line 695, in <module>
    fire.Fire()
  File "/environment/miniconda3/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/environment/miniconda3/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/environment/miniconda3/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "[./work_dir/dints_0/scripts/train.py](https://vscode-remote+ssh-002dremote-002bfeaturize-0040workspace-002efeaturize-002ecn-003a58184.vscode-resource.vscode-cdn.net/home/featurize/work_dir/dints_0/scripts/train.py)", line 612, in run
    f"evaluation metric - class {_c + 1}: {metric[2 * _c] / metric[2 * _c + 1]}")
ZeroDivisionError: float division by zero

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
Cell In[28], line 4
      2 for algo_dict in history:
      3     algo = algo_dict[AlgoKeys.ALGO]
----> 4     algo.train(train_param)  # can use default params by `algo.train()`
      5     acc = algo.get_score()
      6     algo_to_pickle(algo, template_path=algo.template_path, best_metric=acc)

File [~/work_dir/algorithm_templates/dints/scripts/algo.py:472](https://vscode-remote+ssh-002dremote-002bfeaturize-0040workspace-002efeaturize-002ecn-003a58184.vscode-resource.vscode-cdn.net/home/featurize/~/work_dir/algorithm_templates/dints/scripts/algo.py:472), in DintsAlgo.train(self, train_params, search)
    470 cmd, devices_info = self._create_cmd(dints_train_params)
    471 cmd = "OMP_NUM_THREADS=1 " + cmd
--> 472 return self._run_cmd(cmd, devices_info)

File /environment/miniconda3/lib/python3.8/site-packages/monai/apps/auto3dseg/bundle_gen.py:244, in BundleAlgo._run_cmd(self, cmd, devices_info)
    240 cmd_list = cmd_list[_idx:]
    242 logger.info(f"Launching: {' '.join(cmd_list)}")
--> 244 return subprocess.run(cmd_list, env=ps_environ, check=True)

File /environment/miniconda3/lib/python3.8/subprocess.py:516, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    514     retcode = process.poll()
    515     if check and retcode:
--> 516         raise CalledProcessError(retcode, process.args,
    517                                  output=stdout, stderr=stderr)
    518 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['python', '[./work_dir/dints_0/scripts/train.py](https://vscode-remote+ssh-002dremote-002bfeaturize-0040workspace-002efeaturize-002ecn-003a58184.vscode-resource.vscode-cdn.net/home/featurize/work_dir/dints_0/scripts/train.py)', 'run', "--config_file='work_dir/dints_0/configs/hyper_parameters.yaml','work_dir/dints_0/configs/hyper_parameters_search.yaml','work_dir/dints_0/configs/network.yaml','work_dir/dints_0/configs/network_search.yaml','work_dir/dints_0/configs/transforms_infer.yaml','work_dir/dints_0/configs/transforms_train.yaml','work_dir/dints_0/configs/transforms_validate.yaml'", '--training#num_epochs_per_validation=1', '--training#num_images_per_batch=2', '--training#num_epochs=2']' returned non-zero exit status 1.

```

**Comment by simojens** [comment]
Just had the same issue using Autorunner:

```
dints_0 - training ...:   0%|          | 0/23 [00:00<?, ?round/s]
dints_0 - training ...:   0%|          | 0/23 [24:03<?, ?round/s]
Traceback (most recent call last):
  File ".../work_dir/dints_0/scripts/train.py", line 984, in <module>
    fire.Fire()
  File ".../venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File ".../venv/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File ".../venv/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File ".../work_dir/dints_0/scripts/train.py", line 758, in run
    logger.debug(f"evaluation metric - class {_c + 1}: {metric[2 * _c] / metric[2 * _c + 1]}")
ZeroDivisionError: float division by zero
```

(Replaced repo dir with '...')

Was the issue solved?
