### ISSUE TITLE
test error profiling_camelyon_pipeline.ipynb 

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#1401]
**Describe the bug**
```
[2023-05-20T23:10:57.560Z] Running ./pathology/tumor_detection/ignite/profiling_camelyon_pipeline.ipynb
[2023-05-20T23:10:57.560Z] Checking PEP8 compliance...
[2023-05-20T23:10:58.486Z] Running notebook...
[2023-05-20T23:11:05.021Z] MONAI version: 1.2.0rc7+3.g51741650
[2023-05-20T23:11:05.021Z] Numpy version: 1.22.2
[2023-05-20T23:11:05.021Z] Pytorch version: 2.0.0a0+1767026
[2023-05-20T23:11:05.021Z] MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
[2023-05-20T23:11:05.021Z] MONAI rev id: 517416507000d3edc584b586a690d6f7bb63ecef
[2023-05-20T23:11:05.021Z] MONAI __file__: /home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/__init__.py
[2023-05-20T23:11:05.021Z] 
[2023-05-20T23:11:05.021Z] Optional dependencies:
[2023-05-20T23:11:05.021Z] Pytorch Ignite version: 0.4.11
[2023-05-20T23:11:05.021Z] ITK version: 5.3.0
[2023-05-20T23:11:05.021Z] Nibabel version: 5.1.0
[2023-05-20T23:11:05.021Z] scikit-image version: 0.20.0
[2023-05-20T23:11:05.021Z] Pillow version: 9.2.0
[2023-05-20T23:11:05.021Z] Tensorboard version: 2.9.0
[2023-05-20T23:11:05.021Z] gdown version: 4.7.1
[2023-05-20T23:11:05.021Z] TorchVision version: 0.15.0a0
[2023-05-20T23:11:05.021Z] tqdm version: 4.65.0
[2023-05-20T23:11:05.021Z] lmdb version: 1.4.1
[2023-05-20T23:11:05.021Z] psutil version: 5.9.4
[2023-05-20T23:11:05.021Z] pandas version: 1.5.2
[2023-05-20T23:11:05.021Z] einops version: 0.6.1
[2023-05-20T23:11:05.021Z] transformers version: 4.21.3
[2023-05-20T23:11:05.021Z] mlflow version: 2.3.2
[2023-05-20T23:11:05.021Z] pynrrd version: 1.0.0
[2023-05-20T23:11:05.021Z] 
[2023-05-20T23:11:05.021Z] For details about installing the optional dependencies, please visit:
[2023-05-20T23:11:05.021Z]     https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
[2023-05-20T23:11:05.021Z] 
[2023-05-20T23:11:06.388Z] papermill  --progress-bar -k python3
[2023-05-20T23:11:06.644Z] /usr/local/lib/python3.8/dist-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
[2023-05-20T23:11:06.644Z]   warnings.warn(
[2023-05-20T23:12:03.980Z] 
Executing:   0%|          | 0/19 [00:00<?, ?cell/s]
Executing:   5%|▌         | 1/19 [00:01<00:26,  1.48s/cell]
Executing:  32%|███▏      | 6/19 [00:16<00:35,  2.74s/cell]
Executing:  42%|████▏     | 8/19 [00:21<00:29,  2.68s/cell]
Executing:  53%|█████▎    | 10/19 [00:36<00:39,  4.35s/cell]
Executing:  63%|██████▎   | 12/19 [00:54<00:40,  5.72s/cell]
Executing:  68%|██████▊   | 13/19 [00:54<00:28,  4.73s/cell]
Executing:  89%|████████▉ | 17/19 [00:55<00:04,  2.42s/cell]
Executing:  89%|████████▉ | 17/19 [00:57<00:06,  3.37s/cell]
[2023-05-20T23:12:03.980Z] /usr/local/lib/python3.8/dist-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
[2023-05-20T23:12:03.980Z]   warnings.warn(
[2023-05-20T23:12:03.980Z] Traceback (most recent call last):
[2023-05-20T23:12:03.980Z]   File "/usr/local/bin/papermill", line 8, in <module>
[2023-05-20T23:12:03.980Z]     sys.exit(papermill())
[2023-05-20T23:12:03.980Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
[2023-05-20T23:12:03.980Z]     return self.main(*args, **kwargs)
[2023-05-20T23:12:03.980Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
[2023-05-20T23:12:03.980Z]     rv = self.invoke(ctx)
[2023-05-20T23:12:03.980Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
[2023-05-20T23:12:03.980Z]     return ctx.invoke(self.callback, **ctx.params)
[2023-05-20T23:12:03.980Z]   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
[2023-05-20T23:12:03.980Z]     return __callback(*args, **kwargs)
[2023-05-20T23:12:03.980Z]   File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
[2023-05-20T23:12:03.980Z]     return f(get_current_context(), *args, **kwargs)
[2023-05-20T23:12:03.980Z]   File "/usr/local/lib/python3.8/dist-packages/papermill/cli.py", line 250, in papermill
[2023-05-20T23:12:03.980Z]     execute_notebook(
[2023-05-20T23:12:03.980Z]   File "/usr/local/lib/python3.8/dist-packages/papermill/execute.py", line 128, in execute_notebook
[2023-05-20T23:12:03.980Z]     raise_for_execution_errors(nb, output_path)
[2023-05-20T23:12:03.980Z]   File "/usr/local/lib/python3.8/dist-packages/papermill/execute.py", line 232, in raise_for_execution_errors
[2023-05-20T23:12:03.980Z]     raise error
[2023-05-20T23:12:03.980Z] papermill.exceptions.PapermillExecutionError: 
[2023-05-20T23:12:03.980Z] ---------------------------------------------------------------------------
[2023-05-20T23:12:03.980Z] Exception encountered at "In [7]":
[2023-05-20T23:12:03.980Z] ---------------------------------------------------------------------------
[2023-05-20T23:12:03.980Z] EmptyDataError                            Traceback (most recent call last)
[2023-05-20T23:12:03.980Z] Cell In[7], line 2
[2023-05-20T23:12:03.980Z]       1 # Load NVTX Push/Pop Range Summary
[2023-05-20T23:12:03.980Z] ----> 2 summary = pd.read_csv("profile_report_nvtxppsum.csv")
[2023-05-20T23:12:03.980Z]       3 # display(summary)
[2023-05-20T23:12:03.980Z]       4 
[2023-05-20T23:12:03.980Z]       5 # Set the Range (which is the name of each range) as the index
[2023-05-20T23:12:03.980Z]       6 summary.set_index("Range", inplace=True)
[2023-05-20T23:12:03.980Z] 
[2023-05-20T23:12:03.980Z] File /usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:211, in deprecate_kwarg.<locals>._deprecate_kwarg.<locals>.wrapper(*args, **kwargs)
[2023-05-20T23:12:03.980Z]     209     else:
[2023-05-20T23:12:03.980Z]     210         kwargs[new_arg_name] = new_arg_value
[2023-05-20T23:12:03.980Z] --> 211 return func(*args, **kwargs)
[2023-05-20T23:12:03.980Z] 
[2023-05-20T23:12:03.980Z] File /usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
[2023-05-20T23:12:03.980Z]     325 if len(args) > num_allow_args:
[2023-05-20T23:12:03.980Z]     326     warnings.warn(
[2023-05-20T23:12:03.980Z]     327         msg.format(arguments=_format_argument_list(allow_args)),
[2023-05-20T23:12:03.980Z]     328         FutureWarning,
[2023-05-20T23:12:03.980Z]     329         stacklevel=find_stack_level(),
[2023-05-20T23:12:03.980Z]     330     )
[2023-05-20T23:12:03.980Z] --> 331 return func(*args, **kwargs)
[2023-05-20T23:12:03.980Z] 
[2023-05-20T23:12:03.980Z] File /usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py:950, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
[2023-05-20T23:12:03.980Z]     935 kwds_defaults = _refine_defaults_read(
[2023-05-20T23:12:03.980Z]     936     dialect,
[2023-05-20T23:12:03.980Z]     937     delimiter,
[2023-05-20T23:12:03.980Z]    (...)
[2023-05-20T23:12:03.980Z]     946     defaults={"delimiter": ","},
[2023-05-20T23:12:03.980Z]     947 )
[2023-05-20T23:12:03.981Z]     948 kwds.update(kwds_defaults)
[2023-05-20T23:12:03.981Z] --> 950 return _read(filepath_or_buffer, kwds)
[2023-05-20T23:12:03.981Z] 
[2023-05-20T23:12:03.981Z] File /usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py:605, in _read(filepath_or_buffer, kwds)
[2023-05-20T23:12:03.981Z]     602 _validate_names(kwds.get("names", None))
[2023-05-20T23:12:03.981Z]     604 # Create the parser.
[2023-05-20T23:12:03.981Z] --> 605 parser = TextFileReader(filepath_or_buffer, **kwds)
[2023-05-20T23:12:03.981Z]     607 if chunksize or iterator:
[2023-05-20T23:12:03.981Z]     608     return parser
[2023-05-20T23:12:03.981Z] 
[2023-05-20T23:12:03.981Z] File /usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py:1442, in TextFileReader.__init__(self, f, engine, **kwds)
[2023-05-20T23:12:03.981Z]    1439     self.options["has_index_names"] = kwds["has_index_names"]
[2023-05-20T23:12:03.981Z]    1441 self.handles: IOHandles | None = None
[2023-05-20T23:12:03.981Z] -> 1442 self._engine = self._make_engine(f, self.engine)
[2023-05-20T23:12:03.981Z] 
[2023-05-20T23:12:03.981Z] File /usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py:1753, in TextFileReader._make_engine(self, f, engine)
[2023-05-20T23:12:03.981Z]    1750     raise ValueError(msg)
[2023-05-20T23:12:03.981Z]    1752 try:
[2023-05-20T23:12:03.981Z] -> 1753     return mapping[engine](f, **self.options)
[2023-05-20T23:12:03.981Z]    1754 except Exception:
[2023-05-20T23:12:03.981Z]    1755     if self.handles is not None:
[2023-05-20T23:12:03.981Z] 
[2023-05-20T23:12:03.981Z] File /usr/local/lib/python3.8/dist-packages/pandas/io/parsers/c_parser_wrapper.py:79, in CParserWrapper.__init__(self, src, **kwds)
[2023-05-20T23:12:03.981Z]      76     kwds.pop(key, None)
[2023-05-20T23:12:03.981Z]      78 kwds["dtype"] = ensure_dtype_objs(kwds.get("dtype", None))
[2023-05-20T23:12:03.981Z] ---> 79 self._reader = parsers.TextReader(src, **kwds)
[2023-05-20T23:12:03.981Z]      81 self.unnamed_cols = self._reader.unnamed_cols
[2023-05-20T23:12:03.981Z]      83 # error: Cannot determine type of 'names'
[2023-05-20T23:12:03.981Z] 
[2023-05-20T23:12:03.981Z] File /usr/local/lib/python3.8/dist-packages/pandas/_libs/parsers.pyx:554, in pandas._libs.parsers.TextReader.__cinit__()
[2023-05-20T23:12:03.981Z] 
[2023-05-20T23:12:03.981Z] EmptyDataError: No columns to parse from file
```

cc @Nic-Ma @mingxin-zheng

**Comment by wyli** [comment]
looks like a network connectivity issue and now it works fine, closing for now.
