### ISSUE TITLE
model_zoo/TCIA_PROSTATEx_Prostate_MRI_Anatomy_Model.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#1474]
```

Running ./model_zoo/TCIA_PROSTATEx_Prostate_MRI_Anatomy_Model.ipynb
[2023-07-29T00:36:51.083Z] Checking PEP8 compliance...
[2023-07-29T00:36:52.008Z] Running notebook...
[2023-07-29T00:37:01.944Z] MONAI version: 1.2.0+63.g5feb3530
[2023-07-29T00:37:01.944Z] Numpy version: 1.22.2
[2023-07-29T00:37:01.944Z] Pytorch version: 2.1.0a0+4136153
[2023-07-29T00:37:01.945Z] MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
[2023-07-29T00:37:01.945Z] MONAI rev id: 5feb353030e0bb204e21e1de338cd81b5972bb8a
[2023-07-29T00:37:01.945Z] MONAI __file__: /home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/__init__.py
[2023-07-29T00:37:01.945Z] 
[2023-07-29T00:37:01.945Z] Optional dependencies:
[2023-07-29T00:37:01.945Z] Pytorch Ignite version: 0.4.11
[2023-07-29T00:37:01.945Z] ITK version: 5.3.0
[2023-07-29T00:37:01.945Z] Nibabel version: 5.1.0
[2023-07-29T00:37:01.945Z] scikit-image version: 0.21.0
[2023-07-29T00:37:01.945Z] scipy version: 1.10.1
[2023-07-29T00:37:01.945Z] Pillow version: 9.2.0
[2023-07-29T00:37:01.945Z] Tensorboard version: 2.9.0
[2023-07-29T00:37:01.945Z] gdown version: 4.7.1
[2023-07-29T00:37:01.945Z] TorchVision version: 0.16.0a0
[2023-07-29T00:37:01.945Z] tqdm version: 4.65.0
[2023-07-29T00:37:01.945Z] lmdb version: 1.4.1
[2023-07-29T00:37:01.945Z] psutil version: 5.9.4
[2023-07-29T00:37:01.945Z] pandas version: 1.5.2
[2023-07-29T00:37:01.945Z] einops version: 0.6.1
[2023-07-29T00:37:01.945Z] transformers version: 4.21.3
[2023-07-29T00:37:01.945Z] mlflow version: 2.5.0
[2023-07-29T00:37:01.945Z] pynrrd version: 1.0.0
[2023-07-29T00:37:01.945Z] 
[2023-07-29T00:37:01.945Z] For details about installing the optional dependencies, please visit:
[2023-07-29T00:37:01.945Z]     https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
[2023-07-29T00:37:01.945Z] 
[2023-07-29T00:37:04.461Z] papermill  --progress-bar -k python3
[2023-07-29T00:37:04.717Z] /usr/local/lib/python3.10/dist-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
[2023-07-29T00:37:04.717Z]   warnings.warn(
[2023-07-29T00:38:13.963Z] 
Executing:   0%|          | 0/32 [00:00<?, ?cell/s]
Executing:   3%|▎         | 1/32 [00:01<00:46,  1.51s/cell]
Executing:  22%|██▏       | 7/32 [01:03<03:56,  9.44s/cell]
Executing:  28%|██▊       | 9/32 [01:07<02:45,  7.18s/cell]
Executing:  28%|██▊       | 9/32 [01:08<02:55,  7.61s/cell]
[2023-07-29T00:38:13.963Z] /usr/local/lib/python3.10/dist-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
[2023-07-29T00:38:13.963Z]   warnings.warn(
[2023-07-29T00:38:13.963Z] Traceback (most recent call last):
[2023-07-29T00:38:13.963Z]   File "/usr/local/bin/papermill", line 8, in <module>
[2023-07-29T00:38:13.963Z]     sys.exit(papermill())
[2023-07-29T00:38:13.963Z]   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
[2023-07-29T00:38:13.963Z]     return self.main(*args, **kwargs)
[2023-07-29T00:38:13.963Z]   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
[2023-07-29T00:38:13.963Z]     rv = self.invoke(ctx)
[2023-07-29T00:38:13.963Z]   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
[2023-07-29T00:38:13.963Z]     return ctx.invoke(self.callback, **ctx.params)
[2023-07-29T00:38:13.963Z]   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
[2023-07-29T00:38:13.963Z]     return __callback(*args, **kwargs)
[2023-07-29T00:38:13.963Z]   File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 26, in new_func
[2023-07-29T00:38:13.963Z]     return f(get_current_context(), *args, **kwargs)
[2023-07-29T00:38:13.963Z]   File "/usr/local/lib/python3.10/dist-packages/papermill/cli.py", line 250, in papermill
[2023-07-29T00:38:13.963Z]     execute_notebook(
[2023-07-29T00:38:13.963Z]   File "/usr/local/lib/python3.10/dist-packages/papermill/execute.py", line 128, in execute_notebook
[2023-07-29T00:38:13.963Z]     raise_for_execution_errors(nb, output_path)
[2023-07-29T00:38:13.963Z]   File "/usr/local/lib/python3.10/dist-packages/papermill/execute.py", line 232, in raise_for_execution_errors
[2023-07-29T00:38:13.963Z]     raise error
[2023-07-29T00:38:13.963Z] papermill.exceptions.PapermillExecutionError: 
[2023-07-29T00:38:13.963Z] ---------------------------------------------------------------------------
[2023-07-29T00:38:13.963Z] Exception encountered at "In [2]":
[2023-07-29T00:38:13.963Z] ---------------------------------------------------------------------------
[2023-07-29T00:38:13.963Z] ModuleNotFoundError                       Traceback (most recent call last)
[2023-07-29T00:38:13.963Z] Cell In[2], line 15
[2023-07-29T00:38:13.963Z]      12 import pydicom_seg
[2023-07-29T00:38:13.963Z]      14 # for downloading data from TCIA
[2023-07-29T00:38:13.963Z] ---> 15 from tcia_utils import nbia
[2023-07-29T00:38:13.963Z]      17 # This is the most common import command for itkWidgets.
[2023-07-29T00:38:13.963Z]      18 #   The view() function opens an interactive viewer for 2D and 3D
[2023-07-29T00:38:13.963Z]      19 #   data in a variety of formats.
[2023-07-29T00:38:13.963Z]      20 from itkwidgets import view
[2023-07-29T00:38:13.963Z] 
[2023-07-29T00:38:13.963Z] File /usr/local/lib/python3.10/dist-packages/tcia_utils/__init__.py:1
[2023-07-29T00:38:13.963Z] ----> 1 from . import nbia
[2023-07-29T00:38:13.963Z]       2 from . import datacite
[2023-07-29T00:38:13.963Z]       3 from . import pathdb
[2023-07-29T00:38:13.963Z] 
[2023-07-29T00:38:13.963Z] File /usr/local/lib/python3.10/dist-packages/tcia_utils/nbia.py:19
[2023-07-29T00:38:13.963Z]      17 import numpy as np
[2023-07-29T00:38:13.963Z]      18 from ipywidgets import interact
[2023-07-29T00:38:13.963Z] ---> 19 import tkinter, pydicom_seg, rt_utils 
[2023-07-29T00:38:13.963Z]      20 from tkinter import filedialog
[2023-07-29T00:38:13.963Z]      22 class StopExecution(Exception):
[2023-07-29T00:38:13.963Z] 
[2023-07-29T00:38:13.963Z] ModuleNotFoundError: No module named 'tkinter'

```

Perhaps an issue from the latest tcia_utils cc @kirbyju

**Comment by kirbyju** [comment]
Sorry about that.  I think we've resolved the issue.  Please let me know if there are still errors in your next test.

**Comment by KumoLiu** [comment]
Tested in image 1.2.0, no error reports.

**Comment by wyli** [comment]
thank you, closing this now..
