### ISSUE TITLE
module 'aim' has no attribute 'Run'

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/tutorials#1536]
```
07:00:29  /usr/local/lib/python3.10/dist-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
07:00:29    warnings.warn(
07:00:29  Traceback (most recent call last):
07:00:29    File "/usr/local/bin/papermill", line 8, in <module>
07:00:29      sys.exit(papermill())
07:00:29    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
07:00:29      return self.main(*args, **kwargs)
07:00:29    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
07:00:29      rv = self.invoke(ctx)
07:00:29    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
07:00:29      return ctx.invoke(self.callback, **ctx.params)
07:00:29    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
07:00:29      return __callback(*args, **kwargs)
07:00:29    File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
07:00:29      return f(get_current_context(), *args, **kwargs)
07:00:29    File "/usr/local/lib/python3.10/dist-packages/papermill/cli.py", line 250, in papermill
07:00:29      execute_notebook(
07:00:29    File "/usr/local/lib/python3.10/dist-packages/papermill/execute.py", line 128, in execute_notebook
07:00:29      raise_for_execution_errors(nb, output_path)
07:00:29    File "/usr/local/lib/python3.10/dist-packages/papermill/execute.py", line 232, in raise_for_execution_errors
07:00:29      raise error
07:00:29  papermill.exceptions.PapermillExecutionError: 
07:00:29  ---------------------------------------------------------------------------
07:00:29  Exception encountered at "In [6]":
07:00:29  ---------------------------------------------------------------------------
07:00:29  AttributeError                            Traceback (most recent call last)
07:00:29  Cell In[6], line 8
07:00:29        5 track_locally = True
07:00:29        7 if track_locally:
07:00:29  ----> 8     aim_run = aim.Run(experiment=experiment_name)
07:00:29        9 else:
07:00:29       10     remote_tracking_server = "aim://0.0.0.0:53800"
07:00:29  
07:00:29  AttributeError: module 'aim' has no attribute 'Run'
```

**Comment by KumoLiu** [comment]
May related to their new release.

**Comment by wyli** [comment]
currently a workaround is added (https://github.com/Project-MONAI/tutorials/pull/1537), we can consider a fix following the latest usage https://github.com/aimhubio/aim/blob/eae9c2989717a8eb8c3e90c5e3c8e75789eaf320/README.md?plain=1#L350-L353
