### ISSUE TITLE
AttributeError: module 'cgi' has no attribute 'escape'

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#159]
**Describe the bug**
full logs at https://github.com/Project-MONAI/MONAI/runs/2190380080?check_suite_focus=true

locally verified that this comes from a particular version of tensorboard (tensorboard in /opt/conda/lib/python3.8/site-packages (from -r requirements-dev.txt (line 9)) (1.15.9999+nv))
may need to have a min. version of tensorboard in `requirements.txt` of this repo

```
Running ./modules/interpretability/class_lung_lesion.ipynb
Checking PEP8 compliance...
Running notebook...
Before:
    "max_epochs = 100\n",
After:
    "max_epochs = 1\n",
Before:
    "val_interval = 1\n",
After:
    "val_interval = 1\n",

Executing:   0%|          | 0/20 [00:00<?, ?cell/s]
Executing:   5%|▌         | 1/20 [00:00<00:18,  1.02cell/s]
Executing:  10%|█         | 2/20 [00:04<00:33,  1.84s/cell]
Executing:  15%|█▌        | 3/20 [00:07<00:35,  2.10s/cell]
Executing:  20%|██        | 4/20 [00:16<01:05,  4.09s/cell]
Executing:  55%|█████▌    | 11/20 [00:18<00:26,  2.95s/cell]
Executing:  65%|██████▌   | 13/20 [00:35<00:32,  4.61s/cell]
Executing:  70%|███████   | 14/20 [00:35<00:19,  3.29s/cell]
Executing:  75%|███████▌  | 15/20 [00:38<00:16,  3.27s/cell]
Executing:  85%|████████▌ | 17/20 [00:39<00:06,  2.33s/cell]
Executing:  90%|█████████ | 18/20 [00:54<00:12,  6.30s/cell]
Executing: 100%|██████████| 20/20 [00:56<00:00,  4.70s/cell]
Executing: 100%|██████████| 20/20 [00:59<00:00,  2.96s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [14]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-f7bb18f5956d> in <module>
      1 get_ipython().run_line_magic('load_ext', 'tensorboard')
----> 2 get_ipython().run_line_magic('tensorboard', '--logdir logs')

/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2334                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2335             with self.builtin_trap:
-> 2336                 result = fn(*args, **kwargs)
   2337             return result
   2338 

/opt/conda/lib/python3.8/site-packages/tensorboard/notebook.py in _start_magic(line)
    118 def _start_magic(line):
    119   """Implementation of the `%tensorboard` line magic."""
--> 120   return start(line)
    121 
    122 

/opt/conda/lib/python3.8/site-packages/tensorboard/notebook.py in start(args_string)
    156 
    157   if isinstance(start_result, manager.StartLaunched):
--> 158     _display(
    159         port=start_result.info.port,
    160         print_message=False,

/opt/conda/lib/python3.8/site-packages/tensorboard/notebook.py in _display(port, height, print_message, display_handle)
    314       _CONTEXT_NONE: _display_cli,
    315   }[_get_context()]
--> 316   return fn(port=port, height=height, display_handle=display_handle)
    317 
    318 

/opt/conda/lib/python3.8/site-packages/tensorboard/notebook.py in _display_ipython(port, height, display_handle)
    414   """
    415   replacements = [
--> 416       ("%HTML_ID%", cgi.escape(frame_id, quote=True)),
    417       ("%JSON_ID%", json.dumps(frame_id)),
    418       ("%PORT%", "%d" % port),

AttributeError: module 'cgi' has no attribute 'escape'
```

**Comment by rijobro** [comment]
Did we not solve this one elsewhere?

**Comment by rijobro** [comment]
Oh yeah, [here](https://github.com/Project-MONAI/MONAI/pull/1783#issuecomment-801276120). Do you know what the minimum version needs to be for it to work? We could just use the most recent release?
