### ISSUE TITLE
memory requirements for modules/interpretability/covid_classification notebook

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#160]
**Describe the bug**
full logs at https://github.com/Project-MONAI/MONAI/runs/2190380080?check_suite_focus=true

the notebook creates two copies of the network, making it requires relatively large memory to run.
it could be further optimised to release the memory after the first copy is used

```
Running ./modules/interpretability/covid_classification.ipynb
real	1m0.067s
user	1m15.381s
sys	0m20.898s
Checking PEP8 compliance...
Running notebook...
Before:
    "max_epochs = 30\n",
After:
    "max_epochs = 1\n",
Before:
    "val_interval = 1\n",
After:
    "val_interval = 1\n",

Executing:   0%|          | 0/16 [00:00<?, ?cell/s]
Executing:   6%|▋         | 1/16 [00:00<00:14,  1.02cell/s]
Executing:  12%|█▎        | 2/16 [00:05<00:28,  2.06s/cell]
Executing:  19%|█▉        | 3/16 [00:08<00:29,  2.25s/cell]
Executing:  38%|███▊      | 6/16 [00:49<00:56,  5.70s/cell]
Executing:  56%|█████▋    | 9/16 [00:49<00:28,  4.03s/cell]
Executing:  75%|███████▌  | 12/16 [01:01<00:15,  3.93s/cell]
Executing:  75%|███████▌  | 12/16 [01:03<00:21,  5.27s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [8]":
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-7a75aa856b8c> in <module>
     30         inputs, labels = batch_data[0].to(device), batch_data[1].to(device)
     31         opt.zero_grad()
---> 32         outputs = net(inputs)
     33         lossval = loss(outputs, labels)
     34         lossval.backward()

/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    879             result = self._slow_forward(*input, **kwargs)
    880         else:
--> 881             result = self.forward(*input, **kwargs)
    882         for hook in itertools.chain(
    883                 _global_forward_hooks.values(),

/__w/MONAI/MONAI/monai/networks/nets/densenet.py in forward(self, x)
    192 
    193     def forward(self, x: torch.Tensor) -> torch.Tensor:
--> 194         x = self.features(x)
    195         x = self.class_layers(x)
    196         return x

/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    879             result = self._slow_forward(*input, **kwargs)
    880         else:
--> 881             result = self.forward(*input, **kwargs)
    882         for hook in itertools.chain(
    883                 _global_forward_hooks.values(),

/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py in forward(self, input)
    115     def forward(self, input):
    116         for module in self:
--> 117             input = module(input)
    118         return input
    119 

/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    879             result = self._slow_forward(*input, **kwargs)
    880         else:
--> 881             result = self.forward(*input, **kwargs)
    882         for hook in itertools.chain(
    883                 _global_forward_hooks.values(),

/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py in forward(self, input)
    115     def forward(self, input):
    116         for module in self:
--> 117             input = module(input)
    118         return input
    119 

/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    879             result = self._slow_forward(*input, **kwargs)
    880         else:
--> 881             result = self.forward(*input, **kwargs)
    882         for hook in itertools.chain(
    883                 _global_forward_hooks.values(),

/__w/MONAI/MONAI/monai/networks/nets/densenet.py in forward(self, x)
     56     def forward(self, x: torch.Tensor) -> torch.Tensor:
     57         new_features = self.layers(x)
---> 58         return torch.cat([x, new_features], 1)
     59 
     60 

RuntimeError: CUDA out of memory. Tried to allocate 236.00 MiB (GPU 0; 15.75 GiB total capacity; 14.44 GiB already allocated; 63.88 MiB free; 14.53 GiB reserved in total by PyTorch)
```

**Comment by rijobro** [comment]
Hm I don't fully understand this error. It fails during the first pass of the data through the network for the first time. At this point, unless I'm mistaken only 1 network has been created. And it's the `Densenet121` which we use elsewhere in our notebooks. Images are (320,320) with batch size of 100, do you think I should reduce batch size?
