### ISSUE TITLE
monai.utils.module.OptionalImportError: from torch.utils.tensorboard import SummaryWriter (module 'tensorflow' has no attribute 'io')

### ISSUE THREAD

**Issue by angleboy8** [Project-MONAI/tutorials#1613]
When the active learning is performed by using labeled samples, the 3D Slicer （5.6.1 version）suddenly stops the training process. Please how to resovle this problem? Thanks a lot.

The bug is as follows:

Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\monai\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramData\anaconda3\envs\monai\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\monailabel\interfaces\utils\app.py", line 128, in <module>
    run_main()
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\monailabel\interfaces\utils\app.py", line 113, in run_main
    result = a.train(request)
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\monailabel\interfaces\app.py", line 423, in train
    result = task(request, self.datastore())
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\monailabel\tasks\train\basic_train.py", line 466, in __call__
    res = self.train(0, world_size, req, datalist)
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\monailabel\tasks\train\basic_train.py", line 543, in train
    context.evaluator = self._create_evaluator(context)
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\monailabel\tasks\train\basic_train.py", line 647, in _create_evaluator
    val_hanlders: List = self.val_handlers(context)
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\monailabel\tasks\train\basic_train.py", line 342, in val_handlers
    TensorBoardStatsHandler(log_dir=context.events_dir, output_transform=lambda x: None, iteration_log=False),
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\monai\handlers\tensorboard_handlers.py", line 138, in __init__
    super().__init__(summary_writer=summary_writer, log_dir=log_dir)
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\monai\handlers\tensorboard_handlers.py", line 54, in __init__
    self._writer = SummaryWriter(log_dir=log_dir)
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\monai\utils\module.py", line 444, in __call__
    raise self._exception
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\monai\utils\module.py", line 396, in optional_import
    pkg = __import__(module)  # top level module
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
    from ._embedding import get_embedding_info, make_mat, make_sprite, make_tsv, write_pbtxt
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "D:\ProgramData\anaconda3\envs\monai\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
monai.utils.module.OptionalImportError: from torch.utils.tensorboard import SummaryWriter (module 'tensorflow' has no attribute 'io').
For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
[2024-01-13 23:03:25,178] [17472] [ThreadPoolExecutor-1_0] [INFO] (monailabel.utils.async_tasks.utils:83) - Return code: 1

**Comment by KumoLiu** [comment]
Hi @angleboy8, it's more like a version issue, perhaps try to update your tensorboard version.
FYI:
https://stackoverflow.com/questions/60146023/attributeerror-module-tensorflow-has-no-attribute-io
Thanks!
