### ISSUE TITLE
IndexError in modules/resample_benchmark.ipynb

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/tutorials#1722]
```
Running ./modules/resample_benchmark.ipynb
Checking PEP8 compliance...
Running notebook...
MONAI version: 1.3.1+2.g66a2fae4
Numpy version: 1.24.4
Pytorch version: 2.3.0+cu121
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 66a2fae406f8d83a4421edd86a04fa787dbbd091
MONAI __file__: /usr/local/lib/python3.10/dist-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.11
ITK version: 5.4.0
Nibabel version: 5.2.1
scikit-image version: 0.19.3
scipy version: 1.12.0
Pillow version: 7.0.0
Tensorboard version: 2.16.2
gdown version: 5.2.0
TorchVision version: 0.18.0+cu121
tqdm version: 4.66.1
lmdb version: 1.4.1
psutil version: 5.9.4
pandas version: 1.5.3
einops version: 0.7.0
transformers version: 4.40.2
mlflow version: 2.13.0
pynrrd version: 1.0.0
clearml version: 1.16.2rc0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

papermill  --progress-bar --log-output -k python3
/usr/local/lib/python3.10/dist-packages/papermill/iorw.py:149: UserWarning: the file is not specified with any extension : -
  warnings.warn(f"the file is not specified with any extension : {os.path.basename(path)}")

Executing:   0%|          | 0/34 [00:00<?, ?cell/s]
Executing:   3%|▎         | 1/34 [00:01<00:37,  1.14s/cell]
Executing:  12%|█▏        | 4/34 [00:29<03:55,  7.87s/cell]
Executing:  18%|█▊        | 6/34 [00:36<02:48,  6.03s/cell]
Executing:  29%|██▉       | 10/34 [00:38<01:09,  2.89s/cell]
Executing:  41%|████      | 14/34 [00:38<00:32,  1.62s/cell]
Executing:  53%|█████▎    | 18/34 [00:38<00:16,  1.01s/cell]
Executing:  71%|███████   | 24/34 [00:38<00:05,  1.75cell/s]
Executing:  76%|███████▋  | 26/34 [00:39<00:04,  1.98cell/s]
Executing:  82%|████████▏ | 28/34 [00:43<00:05,  1.12cell/s]
Executing:  88%|████████▊ | 30/34 [00:45<00:03,  1.23cell/s]
Executing:  88%|████████▊ | 30/34 [00:47<00:06,  1.57s/cell]
/usr/local/lib/python3.10/dist-packages/papermill/iorw.py:149: UserWarning: the file is not specified with any extension : -
  warnings.warn(f"the file is not specified with any extension : {os.path.basename(path)}")
Traceback (most recent call last):
  File "/usr/local/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/papermill/cli.py", line 235, in papermill
    execute_notebook(
  File "/usr/local/lib/python3.10/dist-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/usr/local/lib/python3.10/dist-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [14]":
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[14], line 7
      5 row[1].imshow(monai_warped_img[d])
      6 row[1].axis("off")
----> 7 row[2].imshow(itk_warped_img[d])
      8 row[2].axis("off")
     10 if i == 0:

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed


real	0m47.902s
user	0m56.003s
sys	0m20.942s
Check failed!
```

**Comment by KumoLiu** [comment]
Like an issue from https://pypi.org/project/itk/#history. Will take a look later.
