### ISSUE TITLE
Maisi debug

### ISSUE THREAD

**Issue by carlpe** [Project-MONAI/tutorials#1756]
Trying to generate some CT data, what am i missing?

```
MONAI version: 1.3.1+27.g8cfbcbab
Numpy version: 1.24.3
Pytorch version: 1.12.1
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 8cfbcbabd1529ef4090fb6f7ffbeef47d6b70cc2
MONAI __file__: /home/<username>/monai/MONAI/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.10
ITK version: 5.3.0
Nibabel version: 5.0.0
scikit-image version: 0.19.3
scipy version: 1.8.1
Pillow version: 10.3.0
Tensorboard version: 2.11.0
gdown version: 4.7.3
TorchVision version: 0.13.1
tqdm version: 4.64.1
lmdb version: 1.4.0
psutil version: 6.0.0
pandas version: 1.5.2
einops version: 0.6.0
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: 1.0.0
clearml version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

/home/contra/monai/MONAI/
output_dir: /home/contra/monai/MONAI/maisi/output
trained_autoencoder_path: /home/contra/monai/MONAI/models/autoencoder_epoch273.pt
trained_diffusion_path: /home/contra/monai/MONAI/models/input_unet3d_data-all_steps1000size512ddpm_random_current_inputx_v1.pt
trained_controlnet_path: /home/contra/monai/MONAI/models/controlnet-20datasets-e20wl100fold0bc_noi_dia_fsize_current.pt
trained_mask_generation_autoencoder_path: /home/contra/monai/MONAI/models/mask_generation_autoencoder.pt
trained_mask_generation_diffusion_path: /home/contra/monai/MONAI/models/mask_generation_diffusion_unet.pt
all_mask_files_base_dir: /home/contra/monai/MONAI/datasets/all_masks_flexible_size_and_spacing_3000
all_mask_files_json: /home/contra/monai/MONAI/configs/candidate_masks_flexible_size_and_spacing_3000.json
all_anatomy_size_conditions_json: /home/contra/monai/MONAI/configs/all_anatomy_size_condtions.json
label_dict_json: /home/contra/monai/MONAI/maisi/configs/label_dict.json
label_dict_remap_json: /home/contra/monai/MONAI/maisi/configs/label_dict_124_to_132.json
Global config variables have been loaded.
num_output_samples: 1
body_region: ['abdomen']
anatomy_list: ['liver']
controllable_anatomy_size: [['hepatic tumor', 0.3], ['liver', 0.5]]
num_inference_steps: 1000
mask_generation_num_inference_steps: 1000
output_size: [256, 256, 256]
image_output_ext: .nii.gz
label_output_ext: .nii.gz
spacing: [1.5, 1.5, 2.0]
autoencoder_sliding_window_infer_size: [48, 48, 48]
autoencoder_sliding_window_infer_overlap: 0.25
Network definition and inference inputs have been loaded.
2024-07-10 13:10:37,159 - INFO - 'dst' model updated: 158 of 206 variables.
All the trained model weights have been loaded.
The generated image/mask pairs will be saved in /home/contra/monai/MONAI/maisi/output.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [01:09<00:00, 14.40it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:07<00:00,  1.09it/s]
Traceback (most recent call last):
  File "/home/contra/monai/MONAI/maisi/maisi.py", line 181, in <module>
    output_filenames = ldm_sampler.sample_multiple_images(args.num_output_samples)
  File "/home/contra/monai/MONAI/maisi/scripts/sample.py", line 642, in sample_multiple_images
    ) = self.prepare_one_mask_and_meta_info(anatomy_size_condtion)
  File "/home/contra/monai/MONAI/maisi/scripts/sample.py", line 833, in prepare_one_mask_and_meta_info
    comebine_label_or = self.sample_one_mask(anatomy_size=anatomy_size_condtion)
  File "/home/contra/monai/MONAI/maisi/scripts/sample.py", line 862, in sample_one_mask
    synthetic_mask = ldm_conditional_sample_one_mask(
  File "/home/contra/monai/MONAI/maisi/scripts/sample.py", line 156, in ldm_conditional_sample_one_mask
    synthetic_mask = torch.softmax(synthetic_mask, dim=1)
RuntimeError: "softmax_kernel_impl" not implemented for 'Half'
```

**Comment by carlpe** [comment]
it was some environment issue, i reinstalled and it works now 😹
