### ISSUE TITLE
Question about MAISI data preprocessing

### ISSUE THREAD

**Issue by johnson111788** [Project-MONAI/tutorials#1793]
Hi,

I'm preparing the data for finetuning MAISI's ControlNet. I have some questions about the 3D VISTA segmentation.

1. How does a VISTA output pseudo label merge with the original label? Is the original label used directly? If it overlaps with other organs, does the original label apply?
2. Should I simply remove the prediction mask of dummy classes in [label_dict](https://github.com/Project-MONAI/tutorials/blob/7f397e5ceeeebba0a48f5a2574cb0f0887ded610/generation/maisi/configs/label_dict.json#L3)? For example, the kidney is set to dummy1.

Thank you in advance for your help. It would be great if you could provide the official implementation of the merging original and pseudo labels.

Best,
Yu-Cheng

**Comment by Can-Zhao** [comment]
Thank you for reaching out! @guopengf

**Comment by guopengf** [comment]
Hi @johnson111788 , 
For Q1: MAISI and VISTA 3D share the label_dict. You don't need to modify the label index of pseudo-labels generated by VISTA3D. If your data contains some ground truth for certain labels in generated pseudo-labels, you can replace those pseudo-labels with the GT. For new labels not existing in pseudo-labels, you can map it to any 8 dummy labels in default label_dict.json for finetuning.
 
For Q2: Please refer to the "Execute batch inference for segmenting everything" section of the VISTA3D bundle in MONAI Model Zoo https://github.com/Project-MONAI/model-zoo/tree/dev/models/vista3d#execute-batch-inference-for-segmenting-everything. 
You may notice the [segmenting everything prompt](https://github.com/Project-MONAI/model-zoo/blob/ae1b8833ddd22f6136528743123dbd8bdc3885b0/models/vista3d/configs/inference.json#L16) in VISTA3D already removed those dummy labels.

**Comment by johnson111788** [comment]
Hi Pengfei,

Thanks for your answer. I've tried using `python -m monai.bundle run --config_file="['configs/inference.json', 'configs/batch_inference.json']" --input_dir="MY_DATA_PATH" --output_dir="./output"` to inference. However, I encounter the following error:

> 
> Traceback (most recent call last):
>   File "/data/yucheng/anaconda/envs/vista/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
>     return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
>   File "/data/yucheng/anaconda/envs/vista/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
>     return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
>   File "/mnt/ccvl15/yucheng/DiffAd/Code/model-zoo/models/vista3d/scripts/monai_trans_utils.py", line 178, in __call__
>     pred[pred == frac] = data["label_prompt"][i - 1].to(pred.dtype)
> IndexError: index 1 is out of bounds for dimension 0 with size 1
> 
[vista-errorlog_ipdb.txt](https://github.com/user-attachments/files/16684173/vista-errorlog_ipdb.txt)

Meaning `data["label_prompt"]` is changed to 1 (Not sure why) and `object_num` does not match the `label_prompt` (`object_num` could be larger than 117, which I'm not sure how could this happen).

[batch_inference.json](https://github.com/Project-MONAI/model-zoo/blob/ae1b8833ddd22f6136528743123dbd8bdc3885b0/models/vista3d/configs/batch_inference.json#L5) seems to set the `label_prompt`  as `@everything_labels`, but the results seem not matching the setting.

It would be great if you could tell me how and where the label_prompt is set and how should I avoid this problem.

<img width="1230" alt="image" src="https://github.com/user-attachments/assets/f6056fee-b54a-4fa5-8b2d-b2d2c3ad66c2">

**Comment by Can-Zhao** [comment]
@heyufan1995 It seems this question is related to Vista3D. Do you have any idea? Thanks.

**Comment by heyufan1995** [comment]
@johnson111788 Hi thanks for the finding. There is a racing condition when InvertD is used along with ThreadDataLoader. The error can be reproduced when the preprocesssing/inversing workload is large and thread dataloader is used.   We have an internal fix but has not been updated to model zoo yet.  It's a short fix you can do it manually. 
![image](https://github.com/user-attachments/assets/8af64678-8026-4d51-94e6-6cae67aea829)
![image](https://github.com/user-attachments/assets/ccd62097-77c0-4597-89ff-0ec8b1bad901)
