### ISSUE TITLE
TypeError: create.<locals>.Validator.__init__() got an unexpected keyword argument 'registry'

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/tutorials#1807]
```
[2024-09-01T16:26:05.898Z] Running ./pathology/tumor_detection/ignite/profiling_camelyon_pipeline.ipynb
[2024-09-01T16:26:05.898Z] Checking PEP8 compliance...
[2024-09-01T16:26:06.154Z] Traceback (most recent call last):
[2024-09-01T16:26:06.154Z]   File "/usr/local/bin/jupytext", line 5, in <module>
[2024-09-01T16:26:06.154Z]     from jupytext.cli import jupytext
[2024-09-01T16:26:06.154Z]   File "/usr/local/lib/python3.10/dist-packages/jupytext/__init__.py", line 9, in <module>
[2024-09-01T16:26:06.154Z]     from .contentsmanager import build_jupytext_contents_manager_class
[2024-09-01T16:26:06.154Z]   File "/usr/local/lib/python3.10/dist-packages/jupytext/contentsmanager.py", line 616, in <module>
[2024-09-01T16:26:06.154Z]     from jupyter_server.services.contents.largefilemanager import LargeFileManager
[2024-09-01T16:26:06.154Z]   File "/usr/local/lib/python3.10/dist-packages/jupyter_server/services/contents/largefilemanager.py", line 7, in <module>
[2024-09-01T16:26:06.154Z]     from jupyter_server.services.contents.filemanager import (
[2024-09-01T16:26:06.154Z]   File "/usr/local/lib/python3.10/dist-packages/jupyter_server/services/contents/filemanager.py", line 36, in <module>
[2024-09-01T16:26:06.154Z]     from .manager import AsyncContentsManager, ContentsManager, copy_pat
[2024-09-01T16:26:06.154Z]   File "/usr/local/lib/python3.10/dist-packages/jupyter_server/services/contents/manager.py", line 16, in <module>
[2024-09-01T16:26:06.154Z]     from jupyter_events import EventLogger
[2024-09-01T16:26:06.154Z]   File "/usr/local/lib/python3.10/dist-packages/jupyter_events/__init__.py", line 3, in <module>
[2024-09-01T16:26:06.154Z]     from .logger import EVENTS_METADATA_VERSION, EventLogger
[2024-09-01T16:26:06.154Z]   File "/usr/local/lib/python3.10/dist-packages/jupyter_events/logger.py", line 19, in <module>
[2024-09-01T16:26:06.154Z]     from .schema import SchemaType
[2024-09-01T16:26:06.154Z]   File "/usr/local/lib/python3.10/dist-packages/jupyter_events/schema.py", line 18, in <module>
[2024-09-01T16:26:06.154Z]     from .validators import draft7_format_checker, validate_schema
[2024-09-01T16:26:06.154Z]   File "/usr/local/lib/python3.10/dist-packages/jupyter_events/validators.py", line 44, in <module>
[2024-09-01T16:26:06.154Z]     JUPYTER_EVENTS_SCHEMA_VALIDATOR = Draft7Validator(
[2024-09-01T16:26:06.154Z] TypeError: create.<locals>.Validator.__init__() got an unexpected keyword argument 'registry'
```

**Comment by KumoLiu** [comment]
The issue occurs after updated the base image to version 24.08, the jupytext version upgraded from 1.16.1 to 1.16.4.
