### ISSUE TITLE
Error while training kits23 task

### ISSUE THREAD

**Issue by anadb** [Project-MONAI/tutorials#1889]
I have the following error during the training on my NVIDIA A100

```Traceback (most recent call last):
  File "/mnt/nvme/tutorials/auto3dseg/tasks/kits23/work_dir/segresnet_0/scripts/train.py", line 27, in <module>
    fire.Fire()
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/nvme/tutorials/auto3dseg/tasks/kits23/work_dir/segresnet_0/scripts/train.py", line 23, in run
    run_segmenter(config_file=config_file, **override)
  File "/mnt/nvme/tutorials/auto3dseg/tasks/kits23/work_dir/segresnet_0/scripts/segmenter.py", line 2202, in run_segmenter
    run_segmenter_worker(0, config_file, kwargs)
  File "/mnt/nvme/tutorials/auto3dseg/tasks/kits23/work_dir/segresnet_0/scripts/segmenter.py", line 2174, in run_segmenter_worker
    best_metric = segmenter.run()
  File "/mnt/nvme/tutorials/auto3dseg/tasks/kits23/work_dir/segresnet_0/scripts/segmenter.py", line 2143, in run
    self.train()
  File "/mnt/nvme/tutorials/auto3dseg/tasks/kits23/work_dir/segresnet_0/scripts/segmenter.py", line 1348, in train
    train_loss, train_acc = self.train_epoch(
  File "/mnt/nvme/tutorials/auto3dseg/tasks/kits23/work_dir/segresnet_0/scripts/segmenter.py", line 1827, in train_epoch
    for idx, batch_data in enumerate(train_loader):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 715, in reraise
    raise exception
multiprocessing.managers.RemoteError:
---------------------------------------------------------------------------
Caught RemoteError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/monai/data/dataset.py", line 108, in __getitem__
    return self._transform(index)
  File "/usr/local/lib/python3.10/dist-packages/monai/data/dataset.py", line 903, in _transform
    data = self._cache[cache_index] = self._load_cache_item(cache_index)
  File "<string>", line 2, in __setitem__
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 833, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 253, in serve_client
    request = recv()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 541, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 164, in recvfds
    raise RuntimeError('received %d items of ancdata' %
RuntimeError: received 0 items of ancdata
---------------------------------------------------------------------------
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/monai/apps/auto3dseg/__main__.py", line 24, in <module>
    fire.Fire(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/monai/apps/auto3dseg/auto_runner.py", line 878, in run
    self._train_algo_in_sequence(history)
  File "/usr/local/lib/python3.10/dist-packages/monai/apps/auto3dseg/auto_runner.py", line 728, in _train_algo_in_sequence
    algo.train(self.train_params, self.device_setting)
  File "/usr/local/lib/python3.10/dist-packages/monai/apps/auto3dseg/bundle_gen.py", line 300, in train
    return self._run_cmd(cmd)
  File "/usr/local/lib/python3.10/dist-packages/monai/apps/auto3dseg/bundle_gen.py", line 277, in _run_cmd
    return run_cmd(cmd.split(), run_cmd_verbose=True, env=ps_environ, check=True)
  File "/usr/local/lib/python3.10/dist-packages/monai/utils/misc.py", line 892, in run_cmd
    return subprocess.run(cmd_list, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/mnt/nvme/tutorials/auto3dseg/tasks/kits23/work_dir/segresnet_0/scripts/train.py', 'run', "--config_file='/mnt/nvme/tutorials/auto3dseg/tasks/kits23/work_dir/segresnet_0/configs/hyper_parameters.yaml'"]' returned non-zero exit status 1```

**Comment by KumoLiu** [comment]
Hi @anadb, did you try with the hello world notebook here? https://github.com/Project-MONAI/tutorials/blob/main/auto3dseg/notebooks/auto3dseg_hello_world.ipynb

Looks like the error indicates an issue with inter-process communication when using multiprocessing in Python, specifically related to resource sharing or passing file descriptors between processes.
Perhaps you can try setting the environment variable TORCH_USE_MULTIPROCESSING=0 to disable PyTorch's custom multiprocessing backend.

Or maybe you can find some helpful information here: https://stackoverflow.com/questions/71642653/how-to-resolve-the-error-runtimeerror-received-0-items-of-ancdata
