### ISSUE TITLE
nightly tests: 

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#232]
**Describe the bug**
3 tutorials are broken because of the recent metrics API updates:
https://github.com/Project-MONAI/MONAI/runs/2809697124?check_suite_focus=true
```
Running ./modules/inverse_transforms_and_test_time_augmentations.ipynb
Checking PEP8 compliance...
Running notebook...
Before:
    "    max_epochs = 20\n",
After:
    "    max_epochs = 1\n",
Before:
    "    val_interval = 1\n",
After:
    "    val_interval = 1\n",

Executing:   0%|          | 0/28 [00:00<?, ?cell/s]
Executing:   4%|▎         | 1/28 [00:00<00:26,  1.03cell/s]
Executing:  11%|█         | 3/28 [00:05<00:35,  1.41s/cell]
Executing:  18%|█▊        | 5/28 [00:07<00:30,  1.31s/cell]
Executing:  32%|███▏      | 9/28 [04:20<06:16, 19.83s/cell]
Executing:  36%|███▌      | 10/28 [05:04<08:08, 27.16s/cell]
Executing:  46%|████▋     | 13/28 [05:07<04:49, 19.29s/cell]
Executing:  54%|█████▎    | 15/28 [05:08<02:57, 13.69s/cell]
Executing:  61%|██████    | 17/28 [05:10<01:48,  9.88s/cell]
Executing:  64%|██████▍   | 18/28 [05:25<01:53, 11.38s/cell]
Executing:  64%|██████▍   | 18/28 [05:27<03:01, 18.18s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [12]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-5358f603c5df> in <module>
     49                         device), val_data["label"].to(device)
     50                     val_outputs = infer_seg(val_images, model)
---> 51                     value, _ = dice_metric(y_pred=val_outputs, y=val_labels)
     52                     metric_count += len(value)
     53                     metric_sum += value.item() * len(value)

ValueError: not enough values to unpack (expected 2, got 1)
```

```
Running ./modules/TorchIO_MONAI_PyTorch_Lightning.ipynb
Checking PEP8 compliance...
Running notebook...

Executing:   0%|          | 0/34 [00:00<?, ?cell/s]
Executing:   3%|▎         | 1/34 [00:00<00:32,  1.02cell/s]
Executing:  12%|█▏        | 4/34 [00:20<01:20,  2.67s/cell]
Executing:  15%|█▍        | 5/34 [00:23<01:21,  2.80s/cell]
Executing:  35%|███▌      | 12/34 [00:34<00:52,  2.40s/cell]
Executing:  50%|█████     | 17/34 [00:34<00:28,  1.69s/cell]
Executing:  53%|█████▎    | 18/34 [00:50<00:26,  1.69s/cell]
Executing:  56%|█████▌    | 19/34 [05:20<11:02, 44.14s/cell]
Executing:  62%|██████▏   | 21/34 [05:22<06:45, 31.22s/cell]
Executing:  71%|███████   | 24/34 [05:23<03:39, 21.90s/cell]
Executing:  71%|███████   | 24/34 [05:25<02:15, 13.55s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-3aacdb30b026> in <module>
      8         labels = logits.argmax(dim=1)
      9         labels_one_hot = torch.nn.functional.one_hot(labels).permute(0, 4, 1, 2, 3)
---> 10         dices, _ = get_dice(labels_one_hot.to(model.device), targets.to(model.device))
     11         all_dices.append(dices.cpu())
     12 all_dices = torch.cat(all_dices)

ValueError: too many values to unpack (expected 2)

```

```
Running ./3d_segmentation/brats_segmentation_3d.ipynb
Checking PEP8 compliance...
Running notebook...
Before:
    "max_epochs = 180\n",
After:
    "max_epochs = 1\n",
Before:
    "val_interval = 2\n",
After:

    "val_interval = 1\n",
Executing:   0%|          | 0/28 [00:00<?, ?cell/s]
Executing:   4%|▎         | 1/28 [00:00<00:26,  1.03cell/s]
Executing:  11%|█         | 3/28 [00:05<00:34,  1.40s/cell]
Executing:  18%|█▊        | 5/28 [00:07<00:30,  1.31s/cell]
Executing:  54%|█████▎    | 15/28 [06:55<02:50, 13.14s/cell]
Executing:  61%|██████    | 17/28 [06:56<01:42,  9.35s/cell]
Executing:  68%|██████▊   | 19/28 [06:58<01:01,  6.83s/cell]
Executing:  75%|███████▌  | 21/28 [09:24<03:07, 26.77s/cell]
Executing:  75%|███████▌  | 21/28 [09:27<03:09, 27.02s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-b75830ab8060> in <module>
     55                 # compute overall mean dice
     56                 value, not_nans = dice_metric(y_pred=val_outputs, y=val_labels)
---> 57                 not_nans = not_nans.item()
     58                 metric_count += not_nans
     59                 metric_sum += value.item() * not_nans

ValueError: only one element tensors can be converted to Python scalars

```

**Comment by Nic-Ma** [comment]
Thanks for your report.
As I described in another ticket, Yiheng will update all tutorials when the decollate_batch is completed.

Thanks.

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/MONAI/issues/2396
