### ISSUE TITLE
cron test errors -- related to decollate?

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#264]
**Describe the bug**
cron test logs: https://github.com/Project-MONAI/MONAI/runs/3053665062?check_suite_focus=true
```
Running ./modules/inverse_transforms_and_test_time_augmentations.ipynb
Checking PEP8 compliance...
Running notebook...
Before:
    "    max_epochs = 20\n",
After:
    "    max_epochs = 1\n",
Before:
    "    val_interval = 1\n",
After:
    "    val_interval = 1\n",

Executing:   0%|          | 0/28 [00:00<?, ?cell/s]
Executing:   4%|▎         | 1/28 [00:00<00:26,  1.02cell/s]
Executing:  11%|█         | 3/28 [00:06<00:37,  1.49s/cell]
Executing:  18%|█▊        | 5/28 [00:08<00:32,  1.42s/cell]
Executing:  32%|███▏      | 9/28 [04:11<06:05, 19.22s/cell]
Executing:  36%|███▌      | 10/28 [05:01<08:29, 28.30s/cell]
Executing:  46%|████▋     | 13/28 [05:04<05:01, 20.11s/cell]
Executing:  54%|█████▎    | 15/28 [05:05<03:05, 14.30s/cell]
Executing:  61%|██████    | 17/28 [05:08<01:54, 10.39s/cell]
Executing:  64%|██████▍   | 18/28 [05:30<02:18, 13.80s/cell]
Executing:  75%|███████▌  | 21/28 [05:32<01:09,  9.89s/cell]
Executing:  82%|████████▏ | 23/28 [05:32<00:34,  6.97s/cell]
Executing:  82%|████████▏ | 23/28 [05:35<01:12, 14.58s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [15]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-5cc1c0e9480f> in <module>
     14     unmodified_data = minimal_transforms(file)
     15     transformed_data = val_transforms(file)
---> 16     seg = infer_seg(transformed_data["image"][None].to(
     17         device), model).detach().cpu()[0]
     18     seg_dict = {"label": seg,

AttributeError: 'list' object has no attribute 'detach'
```
```
Running ./deployment/bentoml/mednist_classifier_bentoml.ipynb
Checking PEP8 compliance...
Running notebook...
Before:
    "max_epochs = 5"
After:
    "max_epochs = 1"

Executing:   0%|          | 0/29 [00:00<?, ?cell/s]
Executing:   3%|▎         | 1/29 [00:00<00:27,  1.03cell/s]
Executing:  10%|█         | 3/29 [00:12<01:01,  2.37s/cell]
Executing:  17%|█▋        | 5/29 [00:14<00:49,  2.05s/cell]
Executing:  24%|██▍       | 7/29 [00:29<01:21,  3.70s/cell]
Executing:  28%|██▊       | 8/29 [00:30<00:55,  2.64s/cell]
Executing:  41%|████▏     | 12/29 [00:32<00:34,  2.02s/cell]
Executing:  45%|████▍     | 13/29 [01:09<03:20, 12.53s/cell]
Executing:  45%|████▍     | 13/29 [01:11<01:27,  5.48s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [8]":
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-1e7441c627e1> in <module>
     11 
     12 
---> 13 trainer.run()

/opt/conda/lib/python3.8/site-packages/monai/engines/trainer.py in run(self)
     54         """
     55         self.scaler = torch.cuda.amp.GradScaler() if self.amp else None
---> 56         super().run()
     57 
     58     def get_train_stats(self) -> Dict[str, float]:

/opt/conda/lib/python3.8/site-packages/monai/engines/workflow.py in run(self)
    247 
    248         """
--> 249         super().run(data=self.data_loader, max_epochs=self.state.max_epochs)
    250 
    251     def _iteration(self, engine: Engine, batchdata: Dict[str, torch.Tensor]):

/opt/conda/lib/python3.8/site-packages/ignite/engine/engine.py in run(self, data, max_epochs, epoch_length, seed)
    699 
    700         self.state.dataloader = data
--> 701         return self._internal_run()
    702 
    703     @staticmethod

/opt/conda/lib/python3.8/site-packages/ignite/engine/engine.py in _internal_run(self)
    772             self._dataloader_iter = None
    773             self.logger.error(f"Engine run is terminating due to exception: {e}")
--> 774             self._handle_exception(e)
    775 
    776         self._dataloader_iter = None

/opt/conda/lib/python3.8/site-packages/ignite/engine/engine.py in _handle_exception(self, e)
    467             self._fire_event(Events.EXCEPTION_RAISED, e)
    468         else:
--> 469             raise e
    470 
    471     @property

/opt/conda/lib/python3.8/site-packages/ignite/engine/engine.py in _internal_run(self)
    749                     self._fire_event(Events.TERMINATE)
    750                 else:
--> 751                     self._fire_event(Events.EPOCH_COMPLETED)
    752                 time_taken += time.time() - handlers_start_time
    753                 # update time wrt handlers

/opt/conda/lib/python3.8/site-packages/ignite/engine/engine.py in _fire_event(self, event_name, *event_args, **event_kwargs)
    422             kwargs.update(event_kwargs)
    423             first, others = ((args[0],), args[1:]) if (args and args[0] == self) else ((), args)
--> 424             func(*first, *(event_args + others), **kwargs)
    425 
    426     def fire_event(self, event_name: Any) -> None:

<ipython-input-8-1e7441c627e1> in _print_loss(engine)
      8 @trainer.on(Events.EPOCH_COMPLETED)
      9 def _print_loss(engine):
---> 10     print(f"Epoch {engine.state.epoch}/{engine.state.max_epochs} Loss: {engine.state.output['loss']}")
     11 
     12 

TypeError: list indices must be integers or slices, not str
```

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Could you please help double confirm the issue with MONAI v0.6?
I think you already tested locally for all the notebooks?

Thanks
