### ISSUE TITLE
cron test error TorchIO_MONAI_PyTorch_Lightning.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#270]
**Describe the bug**
https://github.com/Project-MONAI/MONAI/runs/3063670723?check_suite_focus=true
```
Running ./modules/TorchIO_MONAI_PyTorch_Lightning.ipynb
Checking PEP8 compliance...
Running notebook...

Executing:   0%|          | 0/34 [00:00<?, ?cell/s]
Executing:   3%|▎         | 1/34 [00:00<00:32,  1.00cell/s]
Executing:  12%|█▏        | 4/34 [00:22<01:26,  2.89s/cell]
Executing:  15%|█▍        | 5/34 [00:26<01:30,  3.13s/cell]
Executing:  35%|███▌      | 12/34 [00:28<00:49,  2.26s/cell]
Executing:  35%|███▌      | 12/34 [00:29<00:53,  2.43s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [5]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-1aa93278fa36> in <module>
      1 data.prepare_data()
----> 2 data.setup()
      3 print('Training:  ', len(data.train_set))
      4 print('Validation: ', len(data.val_set))
      5 print('Test:      ', len(data.test_set))

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py in wrapped_fn(*args, **kwargs)
     90             obj._has_prepared_data = True
     91 
---> 92         return fn(*args, **kwargs)
     93 
     94     return wrapped_fn

<ipython-input-3-daad3b3a4cf4> in setup(self, stage)
     79         train_subjects, val_subjects = random_split(self.subjects, splits)
     80 
---> 81         self.preprocess = self.get_preprocessing_transform()
     82         augment = self.get_augmentation_transform()
     83         self.transform = tio.Compose([self.preprocess, augment])

<ipython-input-3-daad3b3a4cf4> in get_preprocessing_transform(self)
     56         preprocess = tio.Compose([
     57             tio.RescaleIntensity((-1, 1)),
---> 58             tio.CropOrPad(self.get_max_shape(self.subjects + self.test_subjects)),
     59             tio.EnsureShapeMultiple(8),  # for the U-Net
     60             tio.OneHot(),

<ipython-input-3-daad3b3a4cf4> in get_max_shape(self, subjects)
     17     def get_max_shape(self, subjects):
     18         import numpy as np
---> 19         dataset = tio.SubjectsDataset(subjects)
     20         shapes = np.array([s.spatial_shape for s in dataset])
     21         return shapes.max(axis=0)

/opt/conda/lib/python3.8/site-packages/torchio/data/dataset.py in __init__(self, subjects, transform, load_getitem)
     64             load_getitem: bool = True,
     65             ):
---> 66         self._parse_subjects_list(subjects)
     67         self._subjects = subjects
     68         self._transform: Optional[Callable]

/opt/conda/lib/python3.8/site-packages/torchio/data/dataset.py in _parse_subjects_list(subjects_list)
    124         # Check that it's not empty
    125         if not subjects_list:
--> 126             raise ValueError('Subjects list is empty')
    127 
    128         # Check each element

ValueError: Subjects list is empty


Check failed!
```

**Comment by wyli** [comment]
perhaps it's a downloading issue I'm looking into this
