### ISSUE TITLE
./modules/interpretability/covid_classification.ipynb cron test error

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#293]
**Describe the bug**
in log https://github.com/Project-MONAI/MONAI/runs/3207649328?check_suite_focus=true
```
Running ./modules/interpretability/covid_classification.ipynb
user	0m15.751s
sys	0m12.975s
Checking PEP8 compliance...
Running notebook...
Before:
    "max_epochs = 30\n",
After:
    "max_epochs = 1\n",
Before:
    "val_interval = 1\n",
After:
    "val_interval = 1\n",

Executing:   0%|          | 0/16 [00:00<?, ?cell/s]
Executing:   6%|▋         | 1/16 [00:00<00:12,  1.25cell/s]
Executing:  12%|█▎        | 2/16 [00:04<00:25,  1.80s/cell]
Executing:  19%|█▉        | 3/16 [00:07<00:25,  1.95s/cell]
Executing:  38%|███▊      | 6/16 [00:49<00:55,  5.57s/cell]
Executing:  50%|█████     | 8/16 [00:49<00:31,  3.93s/cell]
Executing:  50%|█████     | 8/16 [00:50<00:50,  6.26s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [5]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-60c268674b62> in <module>
     54     Lambda(lambda im: im if im.ndim == 2 else im[..., 0]),
     55     AddChannel(),
---> 56     Resize(crop_size, "area"),
     57     ScaleIntensity(),
     58 

/__w/MONAI/MONAI/monai/transforms/spatial/array.py in __init__(self, spatial_size, size_mode, mode, align_corners)
    362         align_corners: Optional[bool] = None,
    363     ) -> None:
--> 364         self.size_mode = look_up_option(size_mode, ["all", "longest"])
    365         self.spatial_size = spatial_size
    366         self.mode: InterpolateMode = look_up_option(mode, InterpolateMode)

/__w/MONAI/MONAI/monai/utils/module.py in look_up_option(opt_str, supported, default)
    108     if edit_dists:
    109         guess_at_spelling = min(edit_dists, key=edit_dists.get)  # type: ignore
--> 110         raise ValueError(
    111             f"By '{opt_str}', did you mean '{guess_at_spelling}'?\n"
    112             + f"'{opt_str}' is not a valid option.\n"

ValueError: By 'area', did you mean 'all'?
'area' is not a valid option.
Available options are {'longest', 'all'}.
```

**Comment by Nic-Ma** [comment]
Thanks for the issue report.
Let me update the call of Resize transform to fix it.

Thanks.
