### ISSUE TITLE
./modules/interpretability/class_lung_lesion.ipynb cron test error

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#294]
**Describe the bug**
log: https://github.com/Project-MONAI/MONAI/runs/3207649328?check_suite_focus=true
```
real	2m1.858s
user	2m6.172s
sys	1m6.959s
Running ./modules/interpretability/class_lung_lesion.ipynb
Checking PEP8 compliance...
Running notebook...
Before:
    "max_epochs = 100\n",
After:
    "max_epochs = 1\n",
Before:
    "val_interval = 1\n",
After:
    "val_interval = 1\n",

Executing:   0%|          | 0/20 [00:00<?, ?cell/s]
Executing:   5%|▌         | 1/20 [00:00<00:18,  1.04cell/s]
Executing:  10%|█         | 2/20 [00:04<00:29,  1.64s/cell]
Executing:  15%|█▌        | 3/20 [00:06<00:31,  1.84s/cell]
Executing:  20%|██        | 4/20 [00:14<00:58,  3.69s/cell]
Executing:  45%|████▌     | 9/20 [00:14<00:28,  2.60s/cell]
Executing:  45%|████▌     | 9/20 [00:16<00:19,  1.80s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [6]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-69164ddf1e13> in <module>
     17         RandFlipd("image", spatial_axis=2, prob=0.5),
     18         RandSpatialCropd("image", roi_size=(64, 64, 40)),
---> 19         Resized("image", win_size, "trilinear", True),
     20         RandRotate90d("image", prob=0.5, spatial_axes=[0, 1]),
     21         EnsureTyped("image"),

/__w/MONAI/MONAI/monai/transforms/spatial/dictionary.py in __init__(self, keys, spatial_size, size_mode, mode, align_corners, allow_missing_keys)
    532         self.mode = ensure_tuple_rep(mode, len(self.keys))
    533         self.align_corners = ensure_tuple_rep(align_corners, len(self.keys))
--> 534         self.resizer = Resize(spatial_size=spatial_size, size_mode=size_mode)
    535 
    536     def __call__(self, data: Mapping[Hashable, np.ndarray]) -> Dict[Hashable, np.ndarray]:

/__w/MONAI/MONAI/monai/transforms/spatial/array.py in __init__(self, spatial_size, size_mode, mode, align_corners)
    362         align_corners: Optional[bool] = None,
    363     ) -> None:
--> 364         self.size_mode = look_up_option(size_mode, ["all", "longest"])
    365         self.spatial_size = spatial_size
    366         self.mode: InterpolateMode = look_up_option(mode, InterpolateMode)

/__w/MONAI/MONAI/monai/utils/module.py in look_up_option(opt_str, supported, default)
    113             + supported_msg
    114         )
--> 115     raise ValueError(f"Unsupported option '{opt_str}', " + supported_msg)
    116 
    117 

ValueError: Unsupported option 'trilinear', Available options are {'longest', 'all'}.
```

**Comment by Nic-Ma** [comment]
Thanks for the issue report.
Let me update the call of `Resize` transform to fix it.

Thanks.
