### ISSUE TITLE
data directory is assumed to start at root instead of current directory 

### ISSUE THREAD

**Issue by robert-s-lee** [Project-MONAI/tutorials#297]
**Describe the bug**

data directory is assumed to start at root instead of current directory.   The issue is encountered from `runexamples.sh` which downloads the data into current directory and then untars into `./workspace`.  However,  the following code from [tutorials/3d_classification/torch/densenet_evaluation_array.py](tutorials/3d_classification/torch/densenet_evaluation_array.py)  with leading `""` is replaced with `/` at run time.

```python
    data_path = os.sep.join(["", "workspace", "data", "medical", "ixi", "IXI-T1"])
```

Proposed change is to use `.` as below (or make it a command line argument)
```python
    data_path = os.sep.join([".", "workspace", "data", "medical", "ixi", "IXI-T1"])
```

**To Reproduce**

- setup the environment
```bash
conda create --yes --name monai python=3.8
conda activate monai
git clone https://github.com/Project-MONAI/tutorials
cd tutorials
pip install -r requirements.txt
```

- run `./runexamples.sh`

```bash
./runexamples.sh   
Running 3d_classification/torch/densenet_training_array.py
MONAI version: 0.6.0
Numpy version: 1.21.1
Pytorch version: 1.9.0
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 0ad9e73639e30f4f1af5a1f4a45da9cb09930179

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.2.1
scikit-image version: 0.18.2
Pillow version: 8.3.1
Tensorboard version: 2.4.1
gdown version: 3.13.0
TorchVision version: 0.10.0
ITK version: 5.1.2
tqdm version: 4.42.1
lmdb version: 1.2.1
psutil version: 5.8.0
pandas version: 1.3.1
einops version: 0.3.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

Traceback (most recent call last):
  File "3d_classification/torch/densenet_training_array.py", line 142, in <module>
    main()
  File "3d_classification/torch/densenet_training_array.py", line 67, in main
    im, label = monai.utils.misc.first(check_loader)
  File "/opt/miniconda3/envs/monai/lib/python3.8/site-packages/monai/utils/misc.py", line 73, in first
    for i in iterable:
  File "/opt/miniconda3/envs/monai/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/miniconda3/envs/monai/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/miniconda3/envs/monai/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/miniconda3/envs/monai/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/miniconda3/envs/monai/lib/python3.8/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/data/medical/ixi/IXI-T1/IXI314-IOP-0889-T1.nii.gz'
```

**Expected behavior**
expect the examples to run

**Screenshots**
see above

**Environment (please complete the following information):**
 - OS osx
 - Python version 3.8
 - MONAI version [e.g. git commit hash]
 - CUDA/cuDNN version N/A
 - GPU models and configuration N/A

**Additional context**

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Could you please help take a look this ticket?

Thanks in advance.

**Comment by robert-s-lee** [comment]
I am making couple of mods to improve testing.   Feel free to assign this to me as I am in a process of making changes.
