### ISSUE TITLE
cron test error: pathology/tumor_detection/ignite/profiling_camelyon_pipeline.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#308]
**Describe the bug**
from the nightly log: https://github.com/Project-MONAI/MONAI/runs/3319164834?check_suite_focus=true
```
real	1m25.421s
user	1m36.764s
sys	0m13.458s
Running ./pathology/tumor_detection/ignite/profiling_camelyon_pipeline.ipynb
Checking PEP8 compliance...
Running notebook...
Error: Couldn't find the keyword "max_epochs", and the notebook wasn't on the list of expected exemptions ("doesnt_contain_max_epochs")..

Check failed!

Executing:   0%|          | 0/13 [00:00<?, ?cell/s]
Executing:   8%|▊         | 1/13 [00:01<00:12,  1.07s/cell]
Executing:  38%|███▊      | 5/13 [00:18<00:16,  2.07s/cell]
Executing:  46%|████▌     | 6/13 [00:19<00:11,  1.70s/cell]
Executing:  62%|██████▏   | 8/13 [00:20<00:06,  1.29s/cell]
Executing:  85%|████████▍ | 11/13 [00:20<00:01,  1.10cell/s]
Executing:  85%|████████▍ | 11/13 [00:20<00:03,  1.87s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [5]":
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-e9fcc49d73ee> in <module>
      1 # Load NVTX Push/Pop Range Summary
----> 2 summary = pd.read_csv("profile_report_nvtxppsum.csv")
      3 # display(summary)
      4 
      5 # Set the Range (which is the name of each range) as the index

/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    686     )
    687 
--> 688     return _read(filepath_or_buffer, kwds)
    689 
    690 

/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    452 
    453     # Create the parser.
--> 454     parser = TextFileReader(fp_or_buf, **kwds)
    455 
    456     if chunksize or iterator:

/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    946             self.options["has_index_names"] = kwds["has_index_names"]
    947 
--> 948         self._make_engine(self.engine)
    949 
    950     def close(self):

/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1178     def _make_engine(self, engine="c"):
   1179         if engine == "c":
-> 1180             self._engine = CParserWrapper(self.f, **self.options)
   1181         else:
   1182             if engine == "python":

/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   2008         kwds["usecols"] = self.usecols
   2009 
-> 2010         self._reader = parsers.TextReader(src, **kwds)
   2011         self.unnamed_cols = self._reader.unnamed_cols
   2012 

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] No such file or directory: 'profile_report_nvtxppsum.csv'
```

**Comment by wyli** [comment]
cc @drbeh

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

Could you please help take a look this ticket?
Please enable the test again when you fixed it.

Thanks in advance.

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/tutorials/pull/310/ https://github.com/Project-MONAI/tutorials/pull/318
