### ISSUE TITLE
cron test error ./acceleration/automatic_mixed_precision.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#313]
**Describe the bug**
from log https://github.com/Project-MONAI/MONAI/runs/3378784431?check_suite_focus=true
also in ./acceleration/fast_training_tutorial.ipynb
```
real	0m16.913s
user	0m30.938s
sys	0m15.474s
Running ./acceleration/automatic_mixed_precision.ipynb
Checking PEP8 compliance...
Running notebook...
Before:
    "    max_epochs = 300\n",
After:
    "    max_epochs = 1\n",
Before:
    "    val_interval = 1  # do validation for every epoch\n",
After:
    "    val_interval = 1  # do validation for every epoch\n",

Executing:   0%|          | 0/32 [00:00<?, ?cell/s]
Executing:   3%|▎         | 1/32 [00:01<00:32,  1.06s/cell]
Executing:  12%|█▎        | 4/32 [00:06<00:35,  1.28s/cell]
Executing:  19%|█▉        | 6/32 [00:08<00:30,  1.18s/cell]
Executing:  31%|███▏      | 10/32 [01:11<02:02,  5.56s/cell]
Executing:  56%|█████▋    | 18/32 [01:57<01:18,  5.60s/cell]
Executing:  56%|█████▋    | 18/32 [01:58<01:31,  6.56s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [8]":
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-a094f2fe2e3b> in <module>
      7     amp_epoch_times,
      8     amp_best,
----> 9 ) = train_process(amp=True)
     10 amp_total_time = time.time() - amp_start
     11 print(

<ipython-input-7-54ef01fa97d3> in train_process(amp)
     53         epoch_loss = 0
     54         step = 0
---> 55         for batch_data in train_loader:
     56             step_start = time.time()
     57             step += 1

/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1201             else:
   1202                 del self._task_info[idx]
-> 1203                 return self._process_data(data)
   1204 
   1205     def _try_put_index(self):

/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1227         self._try_put_index()
   1228         if isinstance(data, ExceptionWrapper):
-> 1229             data.reraise()
   1230         return data
   1231 

/opt/conda/lib/python3.8/site-packages/torch/_utils.py in reraise(self)
    432             # have message field
    433             raise self.exc_type(message=msg)
--> 434         raise self.exc_type(msg)
    435 
    436 

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/monai/transforms/transform.py", line 91, in apply_transform
    return [_apply_transform(transform, item, unpack_items) for item in data]
  File "/opt/conda/lib/python3.8/site-packages/monai/transforms/transform.py", line 91, in <listcomp>
    return [_apply_transform(transform, item, unpack_items) for item in data]
  File "/opt/conda/lib/python3.8/site-packages/monai/transforms/transform.py", line 60, in _apply_transform
    return transform(parameters)
  File "/opt/conda/lib/python3.8/site-packages/monai/transforms/utility/dictionary.py", line 610, in __call__
    return {key: val for key, val in data.items() if key not in self.key_iterator(data)}
  File "/opt/conda/lib/python3.8/site-packages/monai/transforms/utility/dictionary.py", line 610, in <dictcomp>
    return {key: val for key, val in data.items() if key not in self.key_iterator(data)}
  File "/opt/conda/lib/python3.8/site-packages/monai/transforms/transform.py", line 381, in key_iterator
    raise KeyError(f"Key was missing ({key}) and allow_missing_keys==False")
KeyError: 'Key was missing (label_fg) and allow_missing_keys==False'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/monai/data/dataset.py", line 95, in __getitem__
    return self._transform(index)
  File "/opt/conda/lib/python3.8/site-packages/monai/data/dataset.py", line 660, in _transform
    data = apply_transform(_transform, data)
  File "/opt/conda/lib/python3.8/site-packages/monai/transforms/transform.py", line 116, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.utility.dictionary.DeleteItemsd object at 0x7f090fcd9430>
```

**Comment by wyli** [comment]
could you please help look into these new errors? @Nic-Ma

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for raising the ticket.
That's expected error, I already submitted ticket: https://github.com/Project-MONAI/tutorials/issues/312, will totally update this tutorial next week.

Thanks.

**Comment by wyli** [comment]
closed via https://github.com/Project-MONAI/tutorials/pull/315
