### ISSUE TITLE
nightly test error: profiling_camelyon_pipeline.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#317]
**Describe the bug**
```
Running ./pathology/tumor_detection/ignite/profiling_camelyon_pipeline.ipynb
Checking PEP8 compliance...
Running notebook...

Executing:   0%|          | 0/18 [00:00<?, ?cell/s]
Executing:   6%|▌         | 1/18 [00:00<00:16,  1.04cell/s]
Executing:  33%|███▎      | 6/18 [00:07<00:12,  1.06s/cell]
Executing:  39%|███▉      | 7/18 [00:08<00:10,  1.04cell/s]
Executing:  50%|█████     | 9/18 [00:18<00:19,  2.17s/cell]
Executing:  61%|██████    | 11/18 [01:28<01:24, 12.10s/cell]
Executing:  67%|██████▋   | 12/18 [01:30<00:53,  9.00s/cell]
Executing:  89%|████████▉ | 16/18 [01:30<00:12,  6.31s/cell]
Executing:  89%|████████▉ | 16/18 [01:30<00:11,  5.69s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [7]":
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-e9fcc49d73ee> in <module>
     10 
     11 # Normalize each transform range with total average time (percentage of transfom time)
---> 12 summary = summary[["Average", "Minimum", "Maximum", "StdDev"]] / summary["Average"].sum() * 100
     13 summary

/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2910             if is_iterator(key):
   2911                 key = list(key)
-> 2912             indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
   2913 
   2914         # take() does not accept boolean indexers

/opt/conda/lib/python3.8/site-packages/pandas/core/indexing.py in _get_listlike_indexer(self, key, axis, raise_missing)
   1252             keyarr, indexer, new_indexer = ax._reindex_non_unique(keyarr)
   1253 
-> 1254         self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
   1255         return keyarr, indexer
   1256 

/opt/conda/lib/python3.8/site-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1302             if raise_missing:
   1303                 not_found = list(set(key) - set(ax))
-> 1304                 raise KeyError(f"{not_found} not in index")
   1305 
   1306             # we skip the warning on Categorical

KeyError: "['StdDev'] not in index"

```
**Additional context**

**Comment by wyli** [comment]
could you please help here @drbeh, thank in advance!
