### ISSUE TITLE
I use the Spleen 3D segmentation with MONAI tutorials, when using my data input torch.size([1,1,256,256,90]), it appears error.

### ISSUE THREAD

**Issue by SDTaoPeng** [Project-MONAI/tutorials#432]
**Describe the bug**

Please only create issues here relating to the functioning of the tutorials. For all other questions/problems/bugs, please refer to MONAI's [main repository](https://github.com/Project-MONAI/MONAI). For MONAI bugs (not just a problem in the notebook), please create an [issue](https://github.com/Project-MONAI/MONAI/issues). For questions, please use the [Discussions tab](https://github.com/Project-MONAI/MONAI/discussions).

**To Reproduce**
2. Install '....'
3. Run commands '....'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS
 - Python version
 - MONAI version [e.g. git commit hash]
 - CUDA/cuDNN version
 - GPU models and configuration

**Additional context**

**Comment by SDTaoPeng** [comment]
Backend Qt5Agg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "C:\Users\S209850\Pycharm\plugins\python-ce\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\S209850\Pycharm\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Residual_Disease/3D_Pytorch/MONAI_npy_input/main_spleen.py", line 317, in <module>
    outputs = model(inputs)
  File "C:\Users\S209850\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\S209850\Anaconda3\lib\site-packages\monai\networks\nets\unet.py", line 237, in forward
    x = self.model(x)
  File "C:\Users\S209850\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\S209850\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\S209850\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\S209850\Anaconda3\lib\site-packages\monai\networks\layers\simplelayers.py", line 126, in forward
    y = self.submodule(x)
  File "C:\Users\S209850\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\S209850\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\S209850\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\S209850\Anaconda3\lib\site-packages\monai\networks\layers\simplelayers.py", line 129, in forward
    return torch.cat([x, y], dim=self.dim)
RuntimeError: Sizes of tensors must match except in dimension 4. Got 24 and 23 (The offending index is 0)
python-BaseException

**Comment by rijobro** [comment]
Hi, as the issue template clearly states, unless the issue is explicitly with the unchanged notebook, could you please post future questions as a Discussion in the main repository.
For your particular problem, your image has z=90, which isn't a multiple of 8 (there are four lots of stride=2).
