### ISSUE TITLE
nightly build error: ./modules/TorchIO_MONAI_PyTorch_Lightning.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#443]
**Describe the bug**
```python-traceback
Running ./modules/TorchIO_MONAI_PyTorch_Lightning.ipynb
Checking PEP8 compliance...
Running notebook...

Executing:   0%|          | 0/35 [00:00<?, ?cell/s]
Executing:   3%|▎         | 1/35 [00:01<00:43,  1.28s/cell]
Executing:  11%|█▏        | 4/35 [00:04<00:35,  1.14s/cell]
Executing:  14%|█▍        | 5/35 [00:23<02:58,  5.96s/cell]
Executing:  17%|█▋        | 6/35 [00:25<02:24,  4.97s/cell]
Executing:  17%|█▋        | 6/35 [00:26<02:06,  4.35s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [3]":
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_9416/1107065518.py in <module>
      6 import monai
      7 import pandas as pd
----> 8 import torchio as tio
      9 import pytorch_lightning as pl
     10 import matplotlib.pyplot as plt

/opt/conda/lib/python3.8/site-packages/torchio/__init__.py in <module>
      8 from . import utils
      9 from .constants import *  # noqa: F401, F403
---> 10 from .transforms import *  # noqa: F401, F403
     11 from .data import (
     12     io,

/opt/conda/lib/python3.8/site-packages/torchio/transforms/__init__.py in <module>
----> 1 from .transform import Transform
      2 from .fourier import FourierTransform
      3 from .spatial_transform import SpatialTransform
      4 from .intensity_transform import IntensityTransform
      5 

/opt/conda/lib/python3.8/site-packages/torchio/transforms/transform.py in <module>
     11 
     12 from ..utils import to_tuple
---> 13 from ..data.subject import Subject
     14 from ..data.io import nib_to_sitk, sitk_to_nib
     15 from ..data.image import LabelMap

/opt/conda/lib/python3.8/site-packages/torchio/data/__init__.py in <module>
----> 1 from .queue import Queue
      2 from .subject import Subject
      3 from .dataset import SubjectsDataset
      4 from .image import Image, ScalarImage, LabelMap
      5 from .inference import GridAggregator

/opt/conda/lib/python3.8/site-packages/torchio/data/queue.py in <module>
      8 from torch.utils.data import Dataset, DataLoader
      9 
---> 10 from .subject import Subject
     11 from .sampler import PatchSampler
     12 from .dataset import SubjectsDataset

/opt/conda/lib/python3.8/site-packages/torchio/data/subject.py in <module>
      6 
      7 from ..constants import TYPE, INTENSITY
----> 8 from .image import Image
      9 from ..utils import get_subclasses
     10 

/opt/conda/lib/python3.8/site-packages/torchio/data/image.py in <module>
     33 
     34 
---> 35 class Image(dict):
     36     r"""TorchIO image.
     37 

/opt/conda/lib/python3.8/site-packages/torchio/data/image.py in Image()
    189 
    190     @data.setter
--> 191     @deprecated(version='0.18.16', reason=deprecation_message)
    192     def data(self, tensor: TypeData):
    193         self.set_data(tensor)

TypeError: deprecated() got an unexpected keyword argument 'version'
```

**Comment by wyli** [comment]
could you help with this one? @Nic-Ma @yiheng-wang-nv  I couldn't replicate this issue

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Does your PR https://github.com/Project-MONAI/tutorials/pull/444 work for this issue?

Thanks.

**Comment by wyli** [comment]
that PR doesn't fix the issue, I just suspect it's from the incompatible dependencies. cc @fepegar

**Comment by fepegar** [comment]
Thanks, @wyli. I'll take a look at this.

**Comment by wyli** [comment]
> Thanks, @wyli. I'll take a look at this.

thanks, we have this issue since yesterday, perhaps it's matplotlib 3.5 released yesterday https://github.com/matplotlib/matplotlib/releases/tag/v3.5.0

**Comment by fepegar** [comment]
I'm not sure what's going on. `deprecated` is meant to be happy with the `version` kwarg: https://github.com/tantale/deprecated/blame/master/deprecated/classic.py#L86

Is there a specific way to reproduce this? I got no errors on Colab.

**Comment by wyli** [comment]
I can replicate this issue by first installing a previous version:
```
pip install torchio==0.17.21
```
and then run this jupyter notebook locally with `jupyter notebook`
https://github.com/Project-MONAI/tutorials/blob/master/modules/TorchIO_MONAI_PyTorch_Lightning.ipynb

any idea? @fepegar

**Comment by wyli** [comment]
I guess it's the previous version of deprecated polluted the namespace https://github.com/vrcmarcos/python-deprecated/blob/d889719269a5fa469346f8d4888d69fb4f4291c0/deprecated/__init__.py#L19
