### ISSUE TITLE
nightly test: `./modules/csv_datasets.ipynb`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#471]
**Describe the bug**
```py
Running ./modules/csv_datasets.ipynb
Checking PEP8 compliance...
Running notebook...

Executing:   0%|          | 0/31 [00:00<?, ?cell/s]
Executing:   3%|▎         | 1/31 [00:01<00:45,  1.51s/cell]
Executing:  10%|▉         | 3/31 [00:05<00:48,  1.72s/cell]
Executing:  16%|█▌        | 5/31 [00:07<00:35,  1.36s/cell]
Executing:  29%|██▉       | 9/31 [00:16<00:44,  2.01s/cell]
Executing:  35%|███▌      | 11/31 [00:17<00:29,  1.49s/cell]
Executing:  61%|██████▏   | 19/31 [00:17<00:06,  1.75cell/s]
Executing:  61%|██████▏   | 19/31 [00:18<00:11,  1.03cell/s]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [9]":
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_19481/3280160788.py in <module>
----> 1 dataset = CSVDataset(
      2     filename=[filepath1, filepath2, filepath3],
      3     row_indices=[[0, 2], 3],  # load row: 0, 1, 3
      4     col_names=["subject_id", "label", "ehr_1", "ehr_7", "meta_1"],
      5 )

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/utils/deprecate_utils.py in _wrapper(*args, **kwargs)
    208                     warn_deprecated(argname, msg)
    209 
--> 210             return func(*args, **kwargs)
    211 
    212         return _wrapper

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/data/dataset.py in __init__(self, src, row_indices, col_names, col_types, col_groups, transform, **kwargs)
   1277                 raise ValueError("`src` must be file path or pandas `DataFrame`.")
   1278 
-> 1279         data = convert_tables_to_dicts(
   1280             dfs=dfs, row_indices=row_indices, col_names=col_names, col_types=col_types, col_groups=col_groups, **kwargs
   1281         )

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/data/utils.py in convert_tables_to_dicts(dfs, row_indices, col_names, col_types, col_groups, **kwargs)
   1117 
   1118     """
-> 1119     df = reduce(lambda l, r: pd.merge(l, r, **kwargs), ensure_tuple(dfs))
   1120     # parse row indices
   1121     rows: List[Union[int, str]] = []

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/data/utils.py in <lambda>(l, r)
   1117 
   1118     """
-> 1119     df = reduce(lambda l, r: pd.merge(l, r, **kwargs), ensure_tuple(dfs))
   1120     # parse row indices
   1121     rows: List[Union[int, str]] = []

TypeError: merge() got an unexpected keyword argument 'filename'

```

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for raising the error.
I am updating the tutorial to align with our latest API.

Thanks.
