### ISSUE TITLE
cron test: inverse_transforms_and_test_time_augmentations.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#533]
**Describe the bug**
```
Running ./modules/inverse_transforms_and_test_time_augmentations.ipynb
Checking PEP8 compliance...
Running notebook...
Before:
    "    max_epochs = 20\n",
After:
    "    max_epochs = 1\n",
Before:
    "    val_interval = 1\n",
After:
    "    val_interval = 1\n",
/opt/conda/lib/python3.8/site-packages/papermill/iorw.py:58: FutureWarning: pyarrow.HadoopFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
  from pyarrow import HadoopFileSystem

Executing:   0%|          | 0/28 [00:00<?, ?cell/s]
Executing:   4%|▎         | 1/28 [00:01<00:34,  1.28s/cell]
Executing:  11%|█         | 3/28 [00:06<00:56,  2.26s/cell]
Executing:  18%|█▊        | 5/28 [00:08<00:38,  1.66s/cell]
Executing:  32%|███▏      | 9/28 [06:02<16:51, 53.23s/cell]
Executing:  36%|███▌      | 10/28 [07:02<16:20, 54.49s/cell]
Executing:  46%|████▋     | 13/28 [07:05<07:53, 31.58s/cell]
Executing:  54%|█████▎    | 15/28 [07:06<04:53, 22.61s/cell]
Executing:  61%|██████    | 17/28 [07:08<02:58, 16.24s/cell]
Executing:  64%|██████▍   | 18/28 [07:30<02:51, 17.19s/cell]
Executing:  75%|███████▌  | 21/28 [07:32<01:10, 10.10s/cell]
Executing:  82%|████████▏ | 23/28 [07:35<00:38,  7.63s/cell]
Executing:  93%|█████████▎| 26/28 [07:37<00:10,  5.02s/cell]
Executing: 100%|██████████| 28/28 [07:38<00:00,  3.77s/cell]
Executing: 100%|██████████| 28/28 [07:39<00:00, 16.41s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [18]":
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/transforms/transform.py in apply_transform(transform, data, map_items, unpack_items)
     81             return [_apply_transform(transform, item, unpack_items) for item in data]
---> 82         return _apply_transform(transform, data, unpack_items)
     83     except Exception as e:

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/transforms/transform.py in _apply_transform(transform, parameters, unpack_parameters)
     52 
---> 53     return transform(parameters)
     54 

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/transforms/croppad/dictionary.py in inverse(self, data)
    316         for key in self.key_iterator(d):
--> 317             transform = self.get_most_recent_transform(d, key)
    318             # Create inverse transform

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/transforms/inverse.py in get_most_recent_transform(self, data, key)
    136         transform = data[self.trace_key(key)][-1]
--> 137         self.check_transforms_match(transform)
    138         return transform

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/transforms/inverse.py in check_transforms_match(self, transform)
    129             return
--> 130         raise RuntimeError(f"Error inverting the most recently applied invertible transform {xform_name} {xform_id}.")
    131 

RuntimeError: Error inverting the most recently applied invertible transform EnsureTyped 140271422952784.

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_14115/3197073230.py in <module>
     12 for file in np.random.choice(val_files, size=5, replace=False):
     13 
---> 14     mode_tta, mean_tta, std_tta, vvc_tta = tt_aug(file, num_examples=10)
     15     unmodified_data = minimal_transforms(file)
     16 

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/data/test_time_augmentation.py in __call__(self, data, num_examples)
    193             # do model forward pass
    194             batch_data[self._pred_key] = self.inferrer_fn(batch_data[self.image_key].to(self.device))
--> 195             outs.extend([self.inverter(i)[self._pred_key] for i in decollate_batch(batch_data)])
    196 
    197         output: NdarrayOrTensor = stack(outs, 0)

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/data/test_time_augmentation.py in <listcomp>(.0)
    193             # do model forward pass
    194             batch_data[self._pred_key] = self.inferrer_fn(batch_data[self.image_key].to(self.device))
--> 195             outs.extend([self.inverter(i)[self._pred_key] for i in decollate_batch(batch_data)])
    196 
    197         output: NdarrayOrTensor = stack(outs, 0)

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/transforms/post/dictionary.py in __call__(self, data)
    652 
    653             with allow_missing_keys_mode(self.transform):  # type: ignore
--> 654                 inverted = self.transform.inverse(input_dict)
    655 
    656             # save the inverted data

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/transforms/compose.py in inverse(self, data)
    176         # loop backwards over transforms
    177         for t in reversed(invertible_transforms):
--> 178             data = apply_transform(t.inverse, data, self.map_items, self.unpack_items)
    179         return data
    180 

/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/transforms/transform.py in apply_transform(transform, data, map_items, unpack_items)
    104             else:
    105                 _log_stats(data=data)
--> 106         raise RuntimeError(f"applying transform {transform}") from e
    107 
    108 

RuntimeError: applying transform <bound method DivisiblePadd.inverse of <monai.transforms.croppad.dictionary.DivisiblePadd object at 0x7f937c570550>>
```

**Comment by Nic-Ma** [comment]
Fixed by PR: https://github.com/Project-MONAI/MONAI/pull/3762.

Thanks.
