### ISSUE TITLE
test error: ./modules/jupyter_utils.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#569]
**Describe the bug**
```
03:06:50  Running ./modules/jupyter_utils.ipynb
03:06:50  Checking PEP8 compliance...
03:06:51  Running notebook...
03:06:51  Before:
03:06:51      "max_epochs = 10\n",
03:06:51  After:
03:06:51      "max_epochs = 1\n",
03:06:52  /opt/conda/lib/python3.8/site-packages/papermill/iorw.py:58: FutureWarning: pyarrow.HadoopFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
03:06:52    from pyarrow import HadoopFileSystem
03:07:06  
Executing:   0%|          | 0/19 [00:00<?, ?cell/s]
Executing:   5%|▌         | 1/19 [00:01<00:24,  1.33s/cell]
Executing:  16%|█▌        | 3/19 [00:05<00:29,  1.87s/cell]
Executing:  26%|██▋       | 5/19 [00:08<00:23,  1.67s/cell]
Executing:  37%|███▋      | 7/19 [00:09<00:14,  1.19s/cell]
Executing:  47%|████▋     | 9/19 [00:12<00:12,  1.29s/cell]
Executing:  89%|████████▉ | 17/19 [00:12<00:00,  2.22cell/s]
Executing:  89%|████████▉ | 17/19 [00:13<00:01,  1.22cell/s]
03:07:06  Traceback (most recent call last):
03:07:06    File "/opt/conda/bin/papermill", line 8, in <module>
03:07:06      sys.exit(papermill())
03:07:06    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
03:07:06      return self.main(*args, **kwargs)
03:07:06    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
03:07:06      rv = self.invoke(ctx)
03:07:06    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
03:07:06      return ctx.invoke(self.callback, **ctx.params)
03:07:06    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
03:07:06      return __callback(*args, **kwargs)
03:07:06    File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
03:07:06      return f(get_current_context(), *args, **kwargs)
03:07:06    File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
03:07:06      execute_notebook(
03:07:06    File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
03:07:06      raise_for_execution_errors(nb, output_path)
03:07:06    File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
03:07:06      raise error
03:07:06  papermill.exceptions.PapermillExecutionError: 
03:07:06  ---------------------------------------------------------------------------
03:07:06  Exception encountered at "In [8]":
03:07:06  ---------------------------------------------------------------------------
03:07:06  RuntimeError                              Traceback (most recent call last)
03:07:06  /tmp/ipykernel_12713/2399949437.py in <module>
03:07:06  ----> 1 con.plot_status(logger)
03:07:06  
03:07:06  /opt/conda/lib/python3.8/site-packages/monai/utils/jupyter_utils.py in plot_status(self, logger, plot_func)
03:07:06      364         """
03:07:06      365         with self.lock:
03:07:06  --> 366             self.fig, _ = plot_func(title=self.status(), engine=self.engine, logger=logger, fig=self.fig)
03:07:06      367             return self.fig
03:07:06  
03:07:06  /opt/conda/lib/python3.8/site-packages/monai/utils/jupyter_utils.py in plot_engine_status(engine, logger, title, yscale, avg_keys, window_fraction, image_fn, fig, selected_inst)
03:07:06      209 
03:07:06      210             if isinstance(src, dict):
03:07:06  --> 211                 for k, v in src.items():
03:07:06      212                     if isinstance(v, torch.Tensor) and v.ndim >= 4:
03:07:06      213                         image = image_fn(k, v[batch_selected_inst])
03:07:06  
03:07:06  RuntimeError: dictionary changed size during iteration
```

**Comment by wyli** [comment]
Sure, I couldn't replicate this issue locally...it's probably a minor issue. the ci server is down for maintenance today, I'll get back to you with more details when the logs are available.
