### ISSUE TITLE
test error: modules/transfer_mmar.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#585]
**Describe the bug**
```
03:48:16  Running ./modules/transfer_mmar.ipynb
03:48:16  Checking PEP8 compliance...
03:48:17  Running notebook...
03:48:17  Before:
03:48:17      "max_epochs = 50\n",
03:48:17  After:
03:48:17      "max_epochs = 1\n",
03:48:17  Before:
03:48:17      "val_interval = 2\n",
03:48:17  After:
03:48:17      "val_interval = 1\n",
03:48:17  /opt/conda/lib/python3.8/site-packages/papermill/iorw.py:58: FutureWarning: pyarrow.HadoopFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
03:48:17    from pyarrow import HadoopFileSystem
03:51:43  
Executing:   0%|          | 0/30 [00:00<?, ?cell/s]
Executing:   3%|▎         | 1/30 [00:01<00:42,  1.46s/cell]
Executing:  10%|█         | 3/30 [00:05<00:50,  1.88s/cell]
Executing:  13%|█▎        | 4/30 [00:06<00:38,  1.49s/cell]
Executing:  20%|██        | 6/30 [00:08<00:30,  1.29s/cell]
Executing:  37%|███▋      | 11/30 [01:02<02:21,  7.42s/cell]
Executing:  57%|█████▋    | 17/30 [03:20<03:21, 15.53s/cell]
Executing:  70%|███████   | 21/30 [03:20<01:33, 10.40s/cell]
Executing:  70%|███████   | 21/30 [03:21<01:26,  9.60s/cell]
03:51:43  Traceback (most recent call last):
03:51:43    File "/opt/conda/bin/papermill", line 8, in <module>
03:51:43      sys.exit(papermill())
03:51:43    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
03:51:43      return self.main(*args, **kwargs)
03:51:43    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
03:51:43      rv = self.invoke(ctx)
03:51:43    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
03:51:43      return ctx.invoke(self.callback, **ctx.params)
03:51:43    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
03:51:43      return __callback(*args, **kwargs)
03:51:43    File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
03:51:43      return f(get_current_context(), *args, **kwargs)
03:51:43    File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
03:51:43      execute_notebook(
03:51:43    File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
03:51:43      raise_for_execution_errors(nb, output_path)
03:51:43    File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
03:51:43      raise error
03:51:43  papermill.exceptions.PapermillExecutionError: 
03:51:43  ---------------------------------------------------------------------------
03:51:43  Exception encountered at "In [12]":
03:51:43  ---------------------------------------------------------------------------
03:51:43  HTTPError                                 Traceback (most recent call last)
03:51:43  /tmp/ipykernel_21516/1997768389.py in <module>
03:51:43        3 if PRETRAINED:
03:51:43        4     print("using a pretrained model.")
03:51:43  ----> 5     unet_model = load_from_mmar(
03:51:43        6         mmar, mmar_dir=root_dir,
03:51:43        7         map_location=device,
03:51:43  
03:51:43  /opt/conda/lib/python3.8/site-packages/monai/apps/mmars/mmars.py in load_from_mmar(item, mmar_dir, progress, version, map_location, pretrained, weights_only, model_key, api, model_file)
03:51:43      223     if not isinstance(item, Mapping):
03:51:43      224         item = get_model_spec(item)
03:51:43  --> 225     model_dir = download_mmar(item=item, mmar_dir=mmar_dir, progress=progress, version=version, api=api)
03:51:43      226     if model_file is None:
03:51:43      227         model_file = os.path.join("models", "model.pt")
03:51:43  
03:51:43  /opt/conda/lib/python3.8/site-packages/monai/apps/mmars/mmars.py in download_mmar(item, mmar_dir, progress, api, version)
03:51:43      138     mmar_dir = Path(mmar_dir)
03:51:43      139     if api:
03:51:43  --> 140         model_dict = _get_all_ngc_models(item.get(Keys.NAME, f"{item}") if isinstance(item, Mapping) else f"{item}")
03:51:43      141         if len(model_dict) == 0:
03:51:43      142             raise ValueError(f"api query returns no item for pattern {item}.  Please change or shorten it.")
03:51:43  
03:51:43  /opt/conda/lib/python3.8/site-packages/monai/apps/mmars/mmars.py in _get_all_ngc_models(pattern, page_index, page_size)
03:51:43       78     if has_requests:
03:51:43       79         resp = requests_get(full_url)
03:51:43  ---> 80         resp.raise_for_status()
03:51:43       81     else:
03:51:43       82         raise ValueError("NGC API requires requests package.  Please install it.")
03:51:43  
03:51:43  /opt/conda/lib/python3.8/site-packages/requests/models.py in raise_for_status(self)
03:51:43      951 
03:51:43      952         if http_error_msg:
03:51:43  --> 953             raise HTTPError(http_error_msg, response=self)
03:51:43      954 
03:51:43      955     def close(self):
03:51:43  
03:51:43  HTTPError: 400 Client Error:  for url: [https://api.ngc.nvidia.com/v2/search/catalog/resources/MODEL?q=%7B%22query%22:%20%22%22,%20%22orderBy%22:%20%5B%7B%22field%22:%20%22score%22,%20%22value%22:%20%22DESC%22%7D%5D,%20%22queryFields%22:%20%5B%22all%22,%20%22description%22,%20%22displayName%22,%20%22name%22,%20%22resourceId%22%5D,%20%22fields%22:%20%5B%22isPublic%22,%20%22attributes%22,%20%22guestAccess%22,%20%22name%22,%20%22orgName%22,%20%22teamName%22,%20%22displayName%22,%20%22dateModified%22,%20%22labels%22,%20%22description%22%5D,%20%22page%22:%200,%20%22pageSize%22:%2050,%20%22filters%22:%20%5B%7B%22field%22:%20%22name%22,%20%22value%22:%20%22*%7B'id':%20'clara_pt_spleen_ct_segmentation_1',%20'name':%20'clara_pt_spleen_ct_segmentation',%20'file_type':%20'zip',%20'hash_type':%20'md5',%20'hash_val':%20None,%20'model_file':%20'models/model.pt',%20'config_file':%20'config/config_train.json',%20'version':%201%7D*%22%7D%5D%7D](https://api.ngc.nvidia.com/v2/search/catalog/resources/MODEL?q=%7B%22query%22:%20%22%22,%20%22orderBy%22:%20%5B%7B%22field%22:%20%22score%22,%20%22value%22:%20%22DESC%22%7D%5D,%20%22queryFields%22:%20%5B%22all%22,%20%22description%22,%20%22displayName%22,%20%22name%22,%20%22resourceId%22%5D,%20%22fields%22:%20%5B%22isPublic%22,%20%22attributes%22,%20%22guestAccess%22,%20%22name%22,%20%22orgName%22,%20%22teamName%22,%20%22displayName%22,%20%22dateModified%22,%20%22labels%22,%20%22description%22%5D,%20%22page%22:%200,%20%22pageSize%22:%2050,%20%22filters%22:%20%5B%7B%22field%22:%20%22name%22,%20%22value%22:%20%22*%7B)
03:51:43  
03:51:43
```

**Comment by lianggecm** [comment]
I'm running the latest version of transfer_mmar.ipynb on google colab and am still experiencing this "400 Client Error".

**Comment by wyli** [comment]
thanks for reporting, the version query is temporarily down, you can use this `load_from_mmar` command:
```py
unet_model = load_from_mmar(
    item="clara_pt_prostate_mri_segmentation_1",
    mmar_dir=root_dir,
    map_location=device,
    pretrained=True,
    api=False,
    version=1)
```
