### ISSUE TITLE
nightly test error: ./modules/bundles/get_started.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#645]
**Describe the bug**
```
10:27:04  Running ./modules/bundles/get_started.ipynb
10:27:04  Checking PEP8 compliance...
10:27:04  Running notebook...
10:27:05  /opt/conda/lib/python3.8/site-packages/papermill/iorw.py:58: FutureWarning: pyarrow.HadoopFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
10:27:05    from pyarrow import HadoopFileSystem
10:27:13  
Executing:   0%|          | 0/42 [00:00<?, ?cell/s]
Executing:   2%|▏         | 1/42 [00:01<00:54,  1.34s/cell]
Executing:   7%|▋         | 3/42 [00:05<01:10,  1.82s/cell]
Executing:  12%|█▏        | 5/42 [00:08<01:00,  1.63s/cell][IPKernelApp] ERROR | Error in message handler
10:27:13  Traceback (most recent call last):
10:27:13    File "/opt/conda/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 461, in dispatch_queue
10:27:13      await self.process_one()
10:27:13    File "/opt/conda/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 450, in process_one
10:27:13      await dispatch(*args)
10:27:13  TypeError: object NoneType can't be used in 'await' expression
10:27:14  
Executing:  21%|██▏       | 9/42 [00:08<00:24,  1.34cell/s]
Executing:  21%|██▏       | 9/42 [00:09<00:35,  1.07s/cell]
10:27:14  Traceback (most recent call last):
10:27:14    File "/opt/conda/bin/papermill", line 8, in <module>
10:27:14      sys.exit(papermill())
10:27:14    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
10:27:14      return self.main(*args, **kwargs)
10:27:14    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
10:27:14      rv = self.invoke(ctx)
10:27:14    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
10:27:14      return ctx.invoke(self.callback, **ctx.params)
10:27:14    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
10:27:14      return __callback(*args, **kwargs)
10:27:14    File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
10:27:14      return f(get_current_context(), *args, **kwargs)
10:27:14    File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
10:27:14      execute_notebook(
10:27:14    File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
10:27:14      raise_for_execution_errors(nb, output_path)
10:27:14    File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
10:27:14      raise error
10:27:14  papermill.exceptions.PapermillExecutionError: 
10:27:14  ---------------------------------------------------------------------------
10:27:14  Exception encountered at "In [4]":
10:27:14  ---------------------------------------------------------------------------
10:27:14  TypeError                                 Traceback (most recent call last)
10:27:14  Input In [4], in <module>
10:27:14        1 resource = "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task09_Spleen.tar"
10:27:14        2 md5 = "410d4a301da4e5b2f6f86ec3ddba524e"
10:27:14  ----> 4 compressed_file = os.path.join(root_dir, "Task09_Spleen.tar")
10:27:14        5 data_dir = os.path.join(root_dir, "Task09_Spleen")
10:27:14        6 if not os.path.exists(data_dir):
10:27:14  
10:27:14  File /opt/conda/lib/python3.8/posixpath.py:76, in join(a, *p)
10:27:14       71 def join(a, *p):
10:27:14       72     """Join two or more pathname components, inserting '/' as needed.
10:27:14       73     If any component is an absolute path, all previous path components
10:27:14       74     will be discarded.  An empty last part will result in a path that
10:27:14       75     ends with a separator."""
10:27:14  ---> 76     a = os.fspath(a)
10:27:14       77     sep = _get_sep(a)
10:27:14       78     path = a
10:27:14  
10:27:14  TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by wyli** [comment]
@Nic-Ma do you think we should skip this test?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Yes, sure, I think we should skip the tests for bundle get_started notebook, it's not python code actually.

Thanks.
