### ISSUE TITLE
nightly test error `modules/interpretability/cats_and_dogs.ipynb`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#704]
**Describe the bug**
```
01:16:49  Running ./modules/interpretability/cats_and_dogs.ipynb
01:16:49  Checking PEP8 compliance...
01:16:50  Running notebook...
01:16:51  Before:
01:16:51      "max_epochs = 2\n",
01:16:51  After:
01:16:51      "max_epochs = 1\n",
01:16:55  /opt/conda/lib/python3.8/site-packages/papermill/iorw.py:58: FutureWarning: pyarrow.HadoopFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
01:16:55    from pyarrow import HadoopFileSystem
01:17:49  
Executing:   0%|          | 0/18 [00:00<?, ?cell/s]
Executing:   6%|▌         | 1/18 [00:01<00:24,  1.43s/cell]
Executing:  11%|█         | 2/18 [00:04<00:36,  2.29s/cell]
Executing:  22%|██▏       | 4/18 [00:46<03:18, 14.16s/cell]
Executing:  28%|██▊       | 5/18 [00:48<02:14, 10.32s/cell]
Executing:  44%|████▍     | 8/18 [00:49<00:46,  4.70s/cell]
Executing:  50%|█████     | 9/18 [00:52<00:39,  4.35s/cell]
Executing:  56%|█████▌    | 10/18 [00:53<00:27,  3.47s/cell]
Executing:  56%|█████▌    | 10/18 [00:54<00:43,  5.46s/cell]
01:17:49  Traceback (most recent call last):
01:17:49    File "/opt/conda/bin/papermill", line 8, in <module>
01:17:49      sys.exit(papermill())
01:17:49    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
01:17:49      return self.main(*args, **kwargs)
01:17:49    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
01:17:49      rv = self.invoke(ctx)
01:17:49    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
01:17:49      return ctx.invoke(self.callback, **ctx.params)
01:17:49    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
01:17:49      return __callback(*args, **kwargs)
01:17:49    File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
01:17:49      return f(get_current_context(), *args, **kwargs)
01:17:49    File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
01:17:49      execute_notebook(
01:17:49    File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
01:17:49      raise_for_execution_errors(nb, output_path)
01:17:49    File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
01:17:49      raise error
01:17:49  papermill.exceptions.PapermillExecutionError: 
01:17:49  ---------------------------------------------------------------------------
01:17:49  Exception encountered at "In [8]":
01:17:49  ---------------------------------------------------------------------------
01:17:49  ImportError                               Traceback (most recent call last)
01:17:49  Input In [8], in <cell line: 2>()
01:17:49        1 max_epochs = 1
01:17:49  ----> 2 for epoch in trange(max_epochs, desc="Epoch"):
01:17:49        3     loss, acc = 0, 0
01:17:49        4     for data in dl:
01:17:49  
01:17:49  File /opt/conda/lib/python3.8/site-packages/tqdm/notebook.py:323, in tnrange(*args, **kwargs)
01:17:49      318 def tnrange(*args, **kwargs):
01:17:49      319     """
01:17:49      320     A shortcut for `tqdm.notebook.tqdm(xrange(*args), **kwargs)`.
01:17:49      321     On Python3+, `range` is used instead of `xrange`.
01:17:49      322     """
01:17:49  --> 323     return tqdm_notebook(_range(*args), **kwargs)
01:17:49  
01:17:49  File /opt/conda/lib/python3.8/site-packages/tqdm/notebook.py:242, in tqdm_notebook.__init__(self, *args, **kwargs)
01:17:49      240 unit_scale = 1 if self.unit_scale is True else self.unit_scale or 1
01:17:49      241 total = self.total * unit_scale if self.total else self.total
01:17:49  --> 242 self.container = self.status_printer(self.fp, total, self.desc, self.ncols)
01:17:49      243 self.container.pbar = proxy(self)
01:17:49      244 self.displayed = False
01:17:49  
01:17:49  File /opt/conda/lib/python3.8/site-packages/tqdm/notebook.py:118, in tqdm_notebook.status_printer(_, total, desc, ncols)
01:17:49      109 # Fallback to text bar if there's no total
01:17:49      110 # DEPRECATED: replaced with an 'info' style bar
01:17:49      111 # if not total:
01:17:49     (...)
01:17:49      115 
01:17:49      116 # Prepare IPython progress bar
01:17:49      117 if IProgress is None:  # #187 #451 #558 #872
01:17:49  --> 118     raise ImportError(WARN_NOIPYW)
01:17:49      119 if total:
01:17:49      120     pbar = IProgress(min=0, max=total)
01:17:49  
01:17:49  ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```

**Comment by rijobro** [comment]
Presumably switching from `from tqdm.notebook import tqdm, trange` to `from tqdm import tqdm, trange` would solve this?
