### ISSUE TITLE
Runtime error in the Code. I am using Colab with reduced data in train and validation set. And i set the epoch to 100. But this happens

### ISSUE THREAD

**Issue by anirban1513** [Project-MONAI/tutorials#72]
INFO:ignite.engine.engine.SupervisedTrainer:Epoch: 5/100, Iter: 21/66 -- train_loss: 0.8563 
ERROR:ignite.engine.engine.SupervisedTrainer:Current run is terminating due to exception: DataLoader worker (pid 1476) is killed by signal: Killed. .
ERROR:ignite.engine.engine.SupervisedTrainer:Exception: DataLoader worker (pid 1476) is killed by signal: Killed. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 811, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "/usr/local/lib/python3.6/dist-packages/monai/engines/trainer.py", line 156, in _iteration
    self.scaler.step(self.optimizer)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/amp/grad_scaler.py", line 320, in step
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/amp/grad_scaler.py", line 320, in <genexpr>
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1476) is killed by signal: Killed. 
ERROR:ignite.engine.engine.SupervisedTrainer:Engine run is terminating due to exception: DataLoader worker (pid 1476) is killed by signal: Killed. .
ERROR:ignite.engine.engine.SupervisedTrainer:Exception: DataLoader worker (pid 1476) is killed by signal: Killed. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 730, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 828, in _run_once_on_dataset
    self._handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 465, in _handle_exception
    self._fire_event(Events.EXCEPTION_RAISED, e)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 423, in _fire_event
    func(*first, *(event_args + others), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/monai/handlers/stats_handler.py", line 145, in exception_raised
    raise e
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 811, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "/usr/local/lib/python3.6/dist-packages/monai/engines/trainer.py", line 156, in _iteration
    self.scaler.step(self.optimizer)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/amp/grad_scaler.py", line 320, in step
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/amp/grad_scaler.py", line 320, in <genexpr>
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1476) is killed by signal: Killed. 
Traceback (most recent call last):
  File "run_net.py", line 301, in <module>
    train(data_folder=data_folder, model_folder=args.model_folder)
  File "run_net.py", line 211, in train
    trainer.run()
  File "/usr/local/lib/python3.6/dist-packages/monai/engines/trainer.py", line 46, in run
    super().run()
  File "/usr/local/lib/python3.6/dist-packages/monai/engines/workflow.py", line 163, in run
    super().run(data=self.data_loader, max_epochs=self.state.max_epochs)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 691, in run
    return self._internal_run()
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 762, in _internal_run
    self._handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 465, in _handle_exception
    self._fire_event(Events.EXCEPTION_RAISED, e)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 423, in _fire_event
    func(*first, *(event_args + others), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/monai/handlers/stats_handler.py", line 145, in exception_raised
    raise e
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 730, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 828, in _run_once_on_dataset
    self._handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 465, in _handle_exception
    self._fire_event(Events.EXCEPTION_RAISED, e)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 423, in _fire_event
    func(*first, *(event_args + others), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/monai/handlers/stats_handler.py", line 145, in exception_raised
    raise e
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 811, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "/usr/local/lib/python3.6/dist-packages/monai/engines/trainer.py", line 156, in _iteration
    self.scaler.step(self.optimizer)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/amp/grad_scaler.py", line 320, in step
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/amp/grad_scaler.py", line 320, in <genexpr>
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1476) is killed by signal: Killed.

**Comment by Nic-Ma** [comment]
Hi @anirban1513 ,

Thanks for your interest here.
Does it always fail with this error or just happened once?
@wyli , it's very slow for me to open Colab page, if really an error, may need your help to test it.

Thanks.

**Comment by wyli** [comment]
not sure which tutorial this is about, but looks like your system doesnot have enough RAM, please try the PersistentDataset or LMDBDataset https://github.com/Project-MONAI/tutorials/blob/master/acceleration/dataset_type_performance.ipynb
