### ISSUE TITLE
test error ./modules/tcia_dataset.ipynb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#887]
**Describe the bug**
```
[2022-08-29T23:52:17.072Z] Running ./modules/tcia_dataset.ipynb
[2022-08-29T23:52:17.072Z] Checking PEP8 compliance...
[2022-08-29T23:52:17.637Z] Running notebook...
[2022-08-29T23:52:17.637Z] Before:
[2022-08-29T23:52:17.637Z]     "max_epochs = 1000\n",
[2022-08-29T23:52:17.637Z] After:
[2022-08-29T23:52:17.637Z]     "max_epochs = 1\n",
[2022-08-29T23:52:17.637Z] Before:
[2022-08-29T23:52:17.637Z]     "val_interval = 2\n",
[2022-08-29T23:52:17.637Z] After:
[2022-08-29T23:52:17.637Z]     "val_interval = 1\n",
[2022-08-29T23:52:21.817Z] MONAI version: 0.9.1+73.gb7974c3e
[2022-08-29T23:52:21.817Z] Numpy version: 1.22.4
[2022-08-29T23:52:21.817Z] Pytorch version: 1.13.0a0+08820cb
[2022-08-29T23:52:21.817Z] MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
[2022-08-29T23:52:21.817Z] MONAI rev id: b7974c3edef8ea5e794b623b3b377a6b473dd758
[2022-08-29T23:52:21.817Z] MONAI __file__: /home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/__init__.py
[2022-08-29T23:52:21.817Z] 
[2022-08-29T23:52:21.817Z] Optional dependencies:
[2022-08-29T23:52:21.817Z] Pytorch Ignite version: 0.4.9
[2022-08-29T23:52:21.817Z] Nibabel version: 4.0.1
[2022-08-29T23:52:21.817Z] scikit-image version: 0.19.3
[2022-08-29T23:52:21.817Z] Pillow version: 9.0.1
[2022-08-29T23:52:21.817Z] Tensorboard version: 2.9.1
[2022-08-29T23:52:21.817Z] gdown version: 4.5.1
[2022-08-29T23:52:21.817Z] TorchVision version: 0.14.0a0
[2022-08-29T23:52:21.817Z] tqdm version: 4.64.0
[2022-08-29T23:52:21.817Z] lmdb version: 1.3.0
[2022-08-29T23:52:21.817Z] psutil version: 5.9.1
[2022-08-29T23:52:21.817Z] pandas version: 1.4.3
[2022-08-29T23:52:21.817Z] einops version: 0.4.1
[2022-08-29T23:52:21.817Z] transformers version: 4.21.2
[2022-08-29T23:52:21.817Z] mlflow version: 1.28.0
[2022-08-29T23:52:21.817Z] pynrrd version: 0.4.3
[2022-08-29T23:52:21.817Z] 
[2022-08-29T23:52:21.817Z] For details about installing the optional dependencies, please visit:
[2022-08-29T23:52:21.817Z]     https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
[2022-08-29T23:52:21.817Z] 
[2022-08-29T23:52:22.748Z] /opt/conda/lib/python3.8/site-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
[2022-08-29T23:52:22.748Z]   warnings.warn(
[2022-08-29T23:52:40.885Z] 
Executing:   0%|          | 0/46 [00:00<?, ?cell/s]
Executing:   2%|▏         | 1/46 [00:01<00:57,  1.28s/cell]
Executing:   9%|▊         | 4/46 [00:06<01:09,  1.65s/cell]
Executing:  11%|█         | 5/46 [00:09<01:28,  2.16s/cell]
Executing:  20%|█▉        | 9/46 [00:17<01:11,  1.94s/cell]
Executing:  20%|█▉        | 9/46 [00:18<01:14,  2.02s/cell]
[2022-08-29T23:52:40.885Z] /opt/conda/lib/python3.8/site-packages/papermill/iorw.py:153: UserWarning: the file is not specified with any extension : -
[2022-08-29T23:52:40.885Z]   warnings.warn(
[2022-08-29T23:52:40.885Z] Traceback (most recent call last):
[2022-08-29T23:52:40.885Z]   File "/opt/conda/bin/papermill", line 8, in <module>
[2022-08-29T23:52:40.885Z]     sys.exit(papermill())
[2022-08-29T23:52:40.885Z]   File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
[2022-08-29T23:52:40.885Z]     return self.main(*args, **kwargs)
[2022-08-29T23:52:40.885Z]   File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
[2022-08-29T23:52:40.885Z]     rv = self.invoke(ctx)
[2022-08-29T23:52:40.885Z]   File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
[2022-08-29T23:52:40.885Z]     return ctx.invoke(self.callback, **ctx.params)
[2022-08-29T23:52:40.885Z]   File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
[2022-08-29T23:52:40.885Z]     return __callback(*args, **kwargs)
[2022-08-29T23:52:40.885Z]   File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
[2022-08-29T23:52:40.885Z]     return f(get_current_context(), *args, **kwargs)
[2022-08-29T23:52:40.885Z]   File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
[2022-08-29T23:52:40.885Z]     execute_notebook(
[2022-08-29T23:52:40.885Z]   File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 128, in execute_notebook
[2022-08-29T23:52:40.885Z]     raise_for_execution_errors(nb, output_path)
[2022-08-29T23:52:40.885Z]   File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 232, in raise_for_execution_errors
[2022-08-29T23:52:40.885Z]     raise error
[2022-08-29T23:52:40.885Z] papermill.exceptions.PapermillExecutionError: 
[2022-08-29T23:52:40.885Z] ---------------------------------------------------------------------------
[2022-08-29T23:52:40.885Z] Exception encountered at "In [4]":
[2022-08-29T23:52:40.885Z] ---------------------------------------------------------------------------
[2022-08-29T23:52:40.885Z] JSONDecodeError                           Traceback (most recent call last)
[2022-08-29T23:52:40.885Z] File /opt/conda/lib/python3.8/site-packages/requests/models.py:910, in Response.json(self, **kwargs)
[2022-08-29T23:52:40.885Z]     909 try:
[2022-08-29T23:52:40.885Z] --> 910     return complexjson.loads(self.text, **kwargs)
[2022-08-29T23:52:40.885Z]     911 except JSONDecodeError as e:
[2022-08-29T23:52:40.885Z]     912     # Catch JSON-related errors and raise as requests.JSONDecodeError
[2022-08-29T23:52:40.885Z]     913     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
[2022-08-29T23:52:40.885Z] 
[2022-08-29T23:52:40.885Z] File /opt/conda/lib/python3.8/json/__init__.py:357, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
[2022-08-29T23:52:40.885Z]     354 if (cls is None and object_hook is None and
[2022-08-29T23:52:40.885Z]     355         parse_int is None and parse_float is None and
[2022-08-29T23:52:40.885Z]     356         parse_constant is None and object_pairs_hook is None and not kw):
[2022-08-29T23:52:40.885Z] --> 357     return _default_decoder.decode(s)
[2022-08-29T23:52:40.885Z]     358 if cls is None:
[2022-08-29T23:52:40.885Z] 
[2022-08-29T23:52:40.885Z] File /opt/conda/lib/python3.8/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
[2022-08-29T23:52:40.885Z]     333 """Return the Python representation of ``s`` (a ``str`` instance
[2022-08-29T23:52:40.885Z]     334 containing a JSON document).
[2022-08-29T23:52:40.885Z]     335 
[2022-08-29T23:52:40.885Z]     336 """
[2022-08-29T23:52:40.885Z] --> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[2022-08-29T23:52:40.885Z]     338 end = _w(s, end).end()
[2022-08-29T23:52:40.885Z] 
[2022-08-29T23:52:40.885Z] File /opt/conda/lib/python3.8/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
[2022-08-29T23:52:40.885Z]     354 except StopIteration as err:
[2022-08-29T23:52:40.885Z] --> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
[2022-08-29T23:52:40.885Z]     356 return obj, end
[2022-08-29T23:52:40.885Z] 
[2022-08-29T23:52:40.885Z] JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-08-29T23:52:40.885Z] 
[2022-08-29T23:52:40.885Z] During handling of the above exception, another exception occurred:
[2022-08-29T23:52:40.885Z] 
[2022-08-29T23:52:40.885Z] JSONDecodeError                           Traceback (most recent call last)
[2022-08-29T23:52:40.885Z] Input In [4], in <cell line: 9>()
[2022-08-29T23:52:40.885Z]      16 clean_modalities = {item['Modality'] for item in modalities}
[2022-08-29T23:52:40.885Z]      17 body_part_url = API_URL + "getbody_partValues?Collection=" + collection_name
[2022-08-29T23:52:40.885Z] ---> 18 body_parts = requests.get(body_part_url).json()
[2022-08-29T23:52:40.885Z]      19 clean_body_parts = set()
[2022-08-29T23:52:40.885Z]      20 for item in body_parts:
[2022-08-29T23:52:40.885Z] 
[2022-08-29T23:52:40.885Z] File /opt/conda/lib/python3.8/site-packages/requests/models.py:917, in Response.json(self, **kwargs)
[2022-08-29T23:52:40.885Z]     915     raise RequestsJSONDecodeError(e.message)
[2022-08-29T23:52:40.885Z]     916 else:
[2022-08-29T23:52:40.885Z] --> 917     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
[2022-08-29T23:52:40.885Z] 
[2022-08-29T23:52:40.885Z] JSONDecodeError: [Errno Expecting value] <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Not Found</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/9.0.52</h3></body></html>: 0
[2022-08-29T23:52:40.885Z] 
```

**Comment by wyli** [comment]
cc @kirbyju I haven't looked into this issue in details but looks like the `getbody_partValues?Collection=` doesn't work. skipping the auto testing for now.

**Comment by kirbyju** [comment]
@wyli This looks like a typo.  There shouldn't be an underscore in the middle of that "getbodypartValues".  I think we also need to update the notebook to tell people that they can only choose SEG modality for segmentations given our email discussions about how RTSTRUCT isn't supported yet.  I'll submit an updated notebook with those changes for your review.
