### ISSUE TITLE
How to modify the loss function as Dice + CE loss?

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [Project-MONAI/tutorials#95]
Hi,
I am conducting a segmentation task with only one target structure. Now I try to modify the loss function as Dice + CE loss, then I just change the code as shown here, 
```
class CrossEntropyLoss(nn.Module):
    def __init__(self):
        super().__init__()
        self.loss = nn.CrossEntropyLoss()

    def forward(self, y_pred, y_true):
        # CrossEntropyLoss target needs to have shape (B, D, H, W)
        # Target from pipeline has shape (B, 1, D, H, W)
        y_true = torch.squeeze(y_true, dim=1).long()
        return self.loss(y_pred, y_true)


class DiceCELoss(nn.Module):
    def __init__(self):
        super().__init__()
        self.dice = monai.losses.DiceLoss(sigmoid = True)
        self.cross_entropy = CrossEntropyLoss()

    def forward(self, y_pred, y_true):
        dice = self.dice(y_pred, y_true)
        cross_entropy = self.cross_entropy(y_pred, y_true)
        return dice + cross_entropy

loss_function = DiceCELoss()
```
However, after changing this part, the code seems cannot work now, and reports such kind of error. Could you please help me find what is wrong?
```
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [34,0,0], thread: [893,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [34,0,0], thread: [894,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [34,0,0], thread: [895,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [34,0,0], thread: [384,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "2D_UNet.py", line 259, in <module>
    main()
  File "2D_UNet.py", line 191, in main
    loss.backward()
  File "/home/anaconda3/envs/monai/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/anaconda3/envs/monai/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

Thanks a lot.

**Comment by Nic-Ma** [comment]
Hi @GOZGOXGOYGO ,

I don't see some obvious error in your loss function, maybe you can compare all your program with:
https://github.com/Project-MONAI/tutorials/blob/master/modules/dynunet_tutorial.ipynb
And please make sure your software env is OK to run a regular PyTorch program.

Thanks.

**Comment by GOZGOXGOYGO** [comment]
Hi,

I think this error might be a bug. Actually, my code can run the monai code with officially provided dice loss. But when I change this part, the code cannot work now. It seems that in the tutorial code, the modified loss function is used with SupervisedTrainer in the following form. But why can't just apply it in this tutorial code? 
https://github.com/Project-MONAI/tutorials/blob/master/2d_segmentation/torch/unet_training_dict.py

Thank you.
```
    trainer = monai.engines.SupervisedTrainer(
        device=device,
        max_epochs=max_epochs,
        train_data_loader=train_loader,
        network=net,
        optimizer=opt,
        loss_function=DiceCELoss(),
        inferer=get_inferer(),
        key_train_metric=None,
        train_handlers=train_handlers,
        amp=amp,
    )
    trainer.run()
```

**Comment by Nic-Ma** [comment]
Hi @GOZGOXGOYGO ,

Could you please help provide a simple program to reproduce your issue? I didn't find any issue at a first look.

Thanks.
